// Code generated by fsgen. DO NOT EDIT.
package food

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"
	"time"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"
)

// Suppress unused imports for packages that may not be needed for all param types.
var (
	_ = fmt.Sprintf
	_ = json.Marshal
	_ = strconv.FormatFloat
	_ = time.UTC
	_ = types.APIInt(0)
	_ = url.Values{}
)

// AddFavoriteRequest holds optional parameters for AddFavorite.
// Nil pointer fields are omitted from the request.
type AddFavoriteRequest struct {
	// FoodID maps to wire param "food_id" (required).
	FoodID *types.APIInt
	// ServingID maps to wire param "serving_id".
	ServingID *types.APIInt
	// NumberOfUnits maps to wire param "number_of_units".
	NumberOfUnits *types.APIFloat
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r AddFavoriteRequest) ToParams() url.Values {
	p := url.Values{}
	if r.FoodID != nil {
		p.Set("food_id", fmt.Sprintf("%d", int64((*r.FoodID))))
	}
	if r.ServingID != nil {
		p.Set("serving_id", fmt.Sprintf("%d", int64((*r.ServingID))))
	}
	if r.NumberOfUnits != nil {
		p.Set("number_of_units", strconv.FormatFloat(float64((*r.NumberOfUnits)), 'f', -1, 64))
	}
	return p
}

// CreateRequest holds optional parameters for Create.
// Nil pointer fields are omitted from the request.
type CreateRequest struct {
	// BrandType maps to wire param "brand_type" (required). Constraint: enum=manufacturer,restaurant,supermarket.
	BrandType *string
	// BrandName maps to wire param "brand_name" (required).
	BrandName *string
	// FoodName maps to wire param "food_name" (required).
	FoodName *string
	// ServingSize maps to wire param "serving_size" (required).
	ServingSize *string
	// Calories maps to wire param "calories" (required).
	Calories *types.APIFloat
	// Fat maps to wire param "fat" (required).
	Fat *types.APIFloat
	// Carbohydrate maps to wire param "carbohydrate" (required).
	Carbohydrate *types.APIFloat
	// Protein maps to wire param "protein" (required).
	Protein *types.APIFloat
	// SaturatedFat maps to wire param "saturated_fat".
	SaturatedFat *types.APIFloat
	// Fiber maps to wire param "fiber".
	Fiber *types.APIFloat
	// Sugar maps to wire param "sugar".
	Sugar *types.APIFloat
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r CreateRequest) ToParams() url.Values {
	p := url.Values{}
	if r.BrandType != nil {
		p.Set("brand_type", (*r.BrandType))
	}
	if r.BrandName != nil {
		p.Set("brand_name", (*r.BrandName))
	}
	if r.FoodName != nil {
		p.Set("food_name", (*r.FoodName))
	}
	if r.ServingSize != nil {
		p.Set("serving_size", (*r.ServingSize))
	}
	if r.Calories != nil {
		p.Set("calories", strconv.FormatFloat(float64((*r.Calories)), 'f', -1, 64))
	}
	if r.Fat != nil {
		p.Set("fat", strconv.FormatFloat(float64((*r.Fat)), 'f', -1, 64))
	}
	if r.Carbohydrate != nil {
		p.Set("carbohydrate", strconv.FormatFloat(float64((*r.Carbohydrate)), 'f', -1, 64))
	}
	if r.Protein != nil {
		p.Set("protein", strconv.FormatFloat(float64((*r.Protein)), 'f', -1, 64))
	}
	if r.SaturatedFat != nil {
		p.Set("saturated_fat", strconv.FormatFloat(float64((*r.SaturatedFat)), 'f', -1, 64))
	}
	if r.Fiber != nil {
		p.Set("fiber", strconv.FormatFloat(float64((*r.Fiber)), 'f', -1, 64))
	}
	if r.Sugar != nil {
		p.Set("sugar", strconv.FormatFloat(float64((*r.Sugar)), 'f', -1, 64))
	}
	return p
}

// DeleteFavoriteRequest holds optional parameters for DeleteFavorite.
// Nil pointer fields are omitted from the request.
type DeleteFavoriteRequest struct {
	// FoodID maps to wire param "food_id" (required).
	FoodID *types.APIInt
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r DeleteFavoriteRequest) ToParams() url.Values {
	p := url.Values{}
	if r.FoodID != nil {
		p.Set("food_id", fmt.Sprintf("%d", int64((*r.FoodID))))
	}
	return p
}

// FindIDForBarcodeRequest holds optional parameters for FindIDForBarcode.
// Nil pointer fields are omitted from the request.
type FindIDForBarcodeRequest struct {
	// Barcode maps to wire param "barcode" (required). Constraint: len=13.
	Barcode *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r FindIDForBarcodeRequest) ToParams() url.Values {
	p := url.Values{}
	if r.Barcode != nil {
		p.Set("barcode", (*r.Barcode))
	}
	return p
}

// GetRequest holds optional parameters for Get.
// Nil pointer fields are omitted from the request.
type GetRequest struct {
	// FoodID maps to wire param "food_id" (required).
	FoodID *types.APIInt
	// IncludeFoodImages maps to wire param "include_food_images" (premier tier only).
	IncludeFoodImages *types.APIBool
	// IncludeFoodAttributes maps to wire param "include_food_attributes" (premier tier only).
	IncludeFoodAttributes *types.APIBool
	// FlagDefaultServing maps to wire param "flag_default_serving".
	FlagDefaultServing *types.APIBool
	// Region maps to wire param "region".
	Region *string
	// Language maps to wire param "language".
	Language *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r GetRequest) ToParams() url.Values {
	p := url.Values{}
	if r.FoodID != nil {
		p.Set("food_id", fmt.Sprintf("%d", int64((*r.FoodID))))
	}
	if r.IncludeFoodImages != nil {
		p.Set("include_food_images", func() string {
			if bool((*r.IncludeFoodImages)) {
				return "1"
			}
			return "0"
		}())
	}
	if r.IncludeFoodAttributes != nil {
		p.Set("include_food_attributes", func() string {
			if bool((*r.IncludeFoodAttributes)) {
				return "1"
			}
			return "0"
		}())
	}
	if r.FlagDefaultServing != nil {
		p.Set("flag_default_serving", func() string {
			if bool((*r.FlagDefaultServing)) {
				return "1"
			}
			return "0"
		}())
	}
	if r.Region != nil {
		p.Set("region", (*r.Region))
	}
	if r.Language != nil {
		p.Set("language", (*r.Language))
	}
	return p
}

// GetV5Request holds optional parameters for GetV5.
// Nil pointer fields are omitted from the request.
type GetV5Request struct {
	// FoodID maps to wire param "food_id" (required).
	FoodID *types.APIInt
	// IncludeSubCategories maps to wire param "include_sub_categories" (premier tier only).
	IncludeSubCategories *types.APIBool
	// IncludeFoodImages maps to wire param "include_food_images" (premier tier only).
	IncludeFoodImages *types.APIBool
	// IncludeFoodAttributes maps to wire param "include_food_attributes" (premier tier only).
	IncludeFoodAttributes *types.APIBool
	// FlagDefaultServing maps to wire param "flag_default_serving".
	FlagDefaultServing *types.APIBool
	// Region maps to wire param "region".
	Region *string
	// Language maps to wire param "language".
	Language *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r GetV5Request) ToParams() url.Values {
	p := url.Values{}
	if r.FoodID != nil {
		p.Set("food_id", fmt.Sprintf("%d", int64((*r.FoodID))))
	}
	if r.IncludeSubCategories != nil {
		p.Set("include_sub_categories", func() string {
			if bool((*r.IncludeSubCategories)) {
				return "1"
			}
			return "0"
		}())
	}
	if r.IncludeFoodImages != nil {
		p.Set("include_food_images", func() string {
			if bool((*r.IncludeFoodImages)) {
				return "1"
			}
			return "0"
		}())
	}
	if r.IncludeFoodAttributes != nil {
		p.Set("include_food_attributes", func() string {
			if bool((*r.IncludeFoodAttributes)) {
				return "1"
			}
			return "0"
		}())
	}
	if r.FlagDefaultServing != nil {
		p.Set("flag_default_serving", func() string {
			if bool((*r.FlagDefaultServing)) {
				return "1"
			}
			return "0"
		}())
	}
	if r.Region != nil {
		p.Set("region", (*r.Region))
	}
	if r.Language != nil {
		p.Set("language", (*r.Language))
	}
	return p
}
