// Code generated by fsgen. DO NOT EDIT.
package food

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"
)

// Suppress unused import when all fields use string type.
var _ = types.APIInt(0)

// Food is a generated response type for the food package.
type Food struct {
	// BrandName — Brand name; present only for Brand food_type
	BrandName *string `json:"brand_name,omitempty"`
	// FoodAttributes — Allergen / preference attributes; Premier tier only
	FoodAttributes *string `json:"food_attributes,omitempty"`
	// FoodID — Unique food identifier
	FoodID types.APIInt `json:"food_id"`
	// FoodImages — Food image URLs; Premier tier + include_food_images=true only
	FoodImages *string `json:"food_images,omitempty"`
	// FoodName — Display name of the food
	FoodName string `json:"food_name"`
	// FoodSubCategories — Sub-category strings; Premier tier + include_sub_categories=true only
	FoodSubCategories *string `json:"food_sub_categories,omitempty"`
	// FoodType — Generic or Brand
	FoodType string `json:"food_type"`
	// FoodURL — FatSecret URL for the food
	FoodURL string `json:"food_url"`
	// Servings — Available serving sizes
	Servings types.FlexSlice[Serving] `json:"servings"`
}

// UnmarshalJSON flattens FatSecret's singular-key wrappers into Food's list
// fields. FatSecret nests these lists one level deeper than the flat struct models
// them (e.g. "servings":{"serving":[...]}), collapses the inner list to a single
// object when exactly one element matches, and emits an empty string — or omits the
// wrapper entirely — when none match. All shapes flatten into the generated slice;
// FlexSlice absorbs the single-object case.
func (f *Food) UnmarshalJSON(b []byte) error {
	// alias breaks UnmarshalJSON recursion so the non-wrapped fields decode with
	// the default struct unmarshaler.
	type alias Food
	aux := struct {
		*alias
		Servings json.RawMessage `json:"servings"`
	}{alias: (*alias)(f)}
	if err := json.Unmarshal(b, &aux); err != nil {
		return err
	}
	if raw := bytes.TrimSpace(aux.Servings); len(raw) != 0 &&
		!bytes.Equal(raw, []byte("null")) && !bytes.Equal(raw, []byte(`""`)) {
		var nested struct {
			Inner types.FlexSlice[Serving] `json:"serving,omitempty"`
		}
		if err := json.Unmarshal(raw, &nested); err != nil {
			return fmt.Errorf("food: decode Food servings: %w", err)
		}
		f.Servings = nested.Inner
	}
	return nil
}

// FoodCreateResult is a generated response type for the food package.
type FoodCreateResult struct {
	// FoodID — Identifier of the newly created food
	FoodID types.APIInt `json:"food_id"`
}

// Serving is a generated response type for the food package.
type Serving struct {
	// AddedSugars — Added sugars in grams; v4+ only
	AddedSugars *types.APIFloat `json:"added_sugars,omitempty"`
	// Calcium — Calcium in mg
	Calcium *types.APIFloat `json:"calcium,omitempty"`
	// Calories — Energy in kcal
	Calories types.APIFloat `json:"calories"`
	// Carbohydrate — Total carbohydrate in grams
	Carbohydrate types.APIFloat `json:"carbohydrate"`
	// Cholesterol — Cholesterol in mg
	Cholesterol *types.APIFloat `json:"cholesterol,omitempty"`
	// Fat — Total fat in grams
	Fat types.APIFloat `json:"fat"`
	// Fiber — Dietary fiber in grams
	Fiber *types.APIFloat `json:"fiber,omitempty"`
	// Iron — Iron in mg
	Iron *types.APIFloat `json:"iron,omitempty"`
	// IsDefault — Whether this is the default serving; Premier tier only
	IsDefault *types.APIBool `json:"is_default,omitempty"`
	// MeasurementDescription — Unit description matching number_of_units
	MeasurementDescription string `json:"measurement_description"`
	// MetricServingAmount — Amount in metric units; absent if no metric equivalent
	MetricServingAmount *types.APIFloat `json:"metric_serving_amount,omitempty"`
	// MetricServingUnit — Metric unit (g, ml, etc.)
	MetricServingUnit *string `json:"metric_serving_unit,omitempty"`
	// MonounsaturatedFat — Monounsaturated fat in grams
	MonounsaturatedFat *types.APIFloat `json:"monounsaturated_fat,omitempty"`
	// NumberOfUnits — Number of serving units
	NumberOfUnits types.APIFloat `json:"number_of_units"`
	// PolyunsaturatedFat — Polyunsaturated fat in grams
	PolyunsaturatedFat *types.APIFloat `json:"polyunsaturated_fat,omitempty"`
	// Potassium — Potassium in mg
	Potassium *types.APIFloat `json:"potassium,omitempty"`
	// Protein — Protein in grams
	Protein types.APIFloat `json:"protein"`
	// SaturatedFat — Saturated fat in grams
	SaturatedFat *types.APIFloat `json:"saturated_fat,omitempty"`
	// ServingDescription — Human-readable serving description (e.g. '1 cup')
	ServingDescription string `json:"serving_description"`
	// ServingID — Unique serving identifier
	ServingID types.APIInt `json:"serving_id"`
	// ServingURL — FatSecret URL for the serving
	ServingURL string `json:"serving_url"`
	// Sodium — Sodium in mg
	Sodium *types.APIFloat `json:"sodium,omitempty"`
	// Sugar — Total sugars in grams
	Sugar *types.APIFloat `json:"sugar,omitempty"`
	// TransFat — Trans fat in grams
	TransFat *types.APIFloat `json:"trans_fat,omitempty"`
	// VitaminA — Vitamin A in mcg
	VitaminA *types.APIFloat `json:"vitamin_a,omitempty"`
	// VitaminC — Vitamin C in mg
	VitaminC *types.APIFloat `json:"vitamin_c,omitempty"`
	// VitaminD — Vitamin D in mcg; v4+ only
	VitaminD *types.APIFloat `json:"vitamin_d,omitempty"`
}

// SuccessResult is a generated response type for the food package.
type SuccessResult struct {
	// Success — 1 on success
	Success types.APIInt `json:"success"`
}
