// Code generated by fsgen. DO NOT EDIT.
package food

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client"
	fserrors "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/errors"
	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"
)

// _ suppresses unused import for packages where all methods use request structs.
var _ = url.Values{}

// Service provides typed access to the food FatSecret API namespace.
type Service interface {
	// AddFavorite calls POST /rest/food/favorite/v1. Auth: oauth1_delegated.
	AddFavorite(ctx context.Context, req AddFavoriteRequest) (SuccessResult, error)
	// Create calls POST /rest/food/v2. Auth: oauth1_delegated.
	Create(ctx context.Context, req CreateRequest) (FoodCreateResult, error)
	// DeleteFavorite calls DELETE /rest/food/favorite/v1. Auth: oauth1_delegated.
	DeleteFavorite(ctx context.Context, req DeleteFavoriteRequest) (SuccessResult, error)
	// FindIDForBarcode calls GET /rest/server.api. Auth: client_credentials. Scope: barcode.
	FindIDForBarcode(ctx context.Context, req FindIDForBarcodeRequest) (Food, error)
	// Get calls GET /rest/food/v4. Auth: client_credentials. Scope: basic.
	Get(ctx context.Context, req GetRequest) (Food, error)
	// GetV5 calls GET /rest/food/v5. Auth: client_credentials. Scope: basic.
	GetV5(ctx context.Context, req GetV5Request) (Food, error)
}

type service struct{ c client.Client }

// New returns a Service bound to the given low-level client.
func New(c client.Client) Service { return &service{c: c} }

// AddFavorite implements Service.AddFavorite.
func (s *service) AddFavorite(ctx context.Context, req AddFavoriteRequest) (SuccessResult, error) {
	var zero SuccessResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "POST",
		Path:   "/rest/food/favorite/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["success"]
	if !ok {
		return zero, fmt.Errorf("food.AddFavorite: response missing key %q", "success")
	}
	var result SuccessResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("food.AddFavorite: unmarshal: %w", err)
	}
	return result, nil
}

// Create implements Service.Create.
func (s *service) Create(ctx context.Context, req CreateRequest) (FoodCreateResult, error) {
	var zero FoodCreateResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "POST",
		Path:   "/rest/food/v2",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["food"]
	if !ok {
		return zero, fmt.Errorf("food.Create: response missing key %q", "food")
	}
	var result FoodCreateResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("food.Create: unmarshal: %w", err)
	}
	return result, nil
}

// DeleteFavorite implements Service.DeleteFavorite.
func (s *service) DeleteFavorite(ctx context.Context, req DeleteFavoriteRequest) (SuccessResult, error) {
	var zero SuccessResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "DELETE",
		Path:   "/rest/food/favorite/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["success"]
	if !ok {
		return zero, fmt.Errorf("food.DeleteFavorite: response missing key %q", "success")
	}
	var result SuccessResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("food.DeleteFavorite: unmarshal: %w", err)
	}
	return result, nil
}

// FindIDForBarcode implements Service.FindIDForBarcode as a two-call composite.
//
// FatSecret's path-style barcode endpoint returns error 101 "API was not resolved";
// only the method-style food.find_id_for_barcode call resolves, and it returns a food_id
// ({"food_id":{"value":"N"}}), not a Food. This method resolves the
// barcode to that id, then delegates to Get to fetch the full food (with servings).
// A food_id of 0 means the barcode is absent from FatSecret's catalog → ErrNotFound.
func (s *service) FindIDForBarcode(ctx context.Context, req FindIDForBarcodeRequest) (Food, error) {
	var zero Food
	params := req.ToParams()
	params.Set("method", "food.find_id_for_barcode")
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/server.api",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["food_id"]
	if !ok {
		return zero, fmt.Errorf("food.FindIDForBarcode: response missing key %q", "food_id")
	}
	var idWrap struct {
		Value types.APIInt `json:"value"`
	}
	if err := json.Unmarshal(raw, &idWrap); err != nil {
		return zero, fmt.Errorf("food.FindIDForBarcode: unmarshal food_id: %w", err)
	}
	if idWrap.Value.Int64() == 0 {
		return zero, fserrors.ErrNotFound
	}
	foodID := idWrap.Value
	flagDefault := types.APIBool(true)
	return s.Get(ctx, GetRequest{FoodID: &foodID, FlagDefaultServing: &flagDefault})
}

// Get implements Service.Get.
func (s *service) Get(ctx context.Context, req GetRequest) (Food, error) {
	var zero Food
	params := req.ToParams()
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/food/v4",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["food"]
	if !ok {
		return zero, fmt.Errorf("food.Get: response missing key %q", "food")
	}
	var result Food
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("food.Get: unmarshal: %w", err)
	}
	return result, nil
}

// GetV5 implements Service.GetV5.
func (s *service) GetV5(ctx context.Context, req GetV5Request) (Food, error) {
	var zero Food
	params := req.ToParams()
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/food/v5",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["food"]
	if !ok {
		return zero, fmt.Errorf("food.GetV5: response missing key %q", "food")
	}
	var result Food
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("food.GetV5: unmarshal: %w", err)
	}
	return result, nil
}
