// Code generated by fsgen. DO NOT EDIT.
package food_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	food "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/api/food"
	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client/mock"
)

// Suppress unused imports for packages where only compile-only tests are generated.
var (
	_ = context.Background
	_ = http.HandlerFunc(nil)
	_ = httptest.NewServer
	_ = strings.HasPrefix
	_ = mock.NewClient
)

// TestSmoke_food_AddFavoriteCompiles verifies the interface and request struct compile.
func TestSmoke_food_AddFavoriteCompiles(t *testing.T) {
	var _ food.Service = food.New(nil)
	_ = food.AddFavoriteRequest{}
}

// TestSmoke_food_CreateCompiles verifies the interface and request struct compile.
func TestSmoke_food_CreateCompiles(t *testing.T) {
	var _ food.Service = food.New(nil)
	_ = food.CreateRequest{}
}

// TestSmoke_food_DeleteFavoriteCompiles verifies the interface and request struct compile.
func TestSmoke_food_DeleteFavoriteCompiles(t *testing.T) {
	var _ food.Service = food.New(nil)
	_ = food.DeleteFavoriteRequest{}
}

// TestSmoke_food_FindIDForBarcodeCompiles verifies the interface and request struct compile.
func TestSmoke_food_FindIDForBarcodeCompiles(t *testing.T) {
	var _ food.Service = food.New(nil)
	_ = food.FindIDForBarcodeRequest{}
}

// TestSmoke_food_GetCompiles verifies the interface and request struct compile.
func TestSmoke_food_GetCompiles(t *testing.T) {
	var _ food.Service = food.New(nil)
	_ = food.GetRequest{}
}

// TestSmoke_food_GetV5Compiles verifies the interface and request struct compile.
func TestSmoke_food_GetV5Compiles(t *testing.T) {
	var _ food.Service = food.New(nil)
	_ = food.GetV5Request{}
}
