// Code generated by fsgen. DO NOT EDIT.
package profile

import (
	"fmt"
	"net/url"
	"strconv"
	"time"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"
)

// Suppress unused imports for packages that may not be needed for all param types.
var (
	_ = fmt.Sprintf
	_ = strconv.FormatFloat
	_ = time.UTC
	_ = types.APIInt(0)
	_ = url.Values{}
)

// CreateRequest holds optional parameters for Create.
// Nil pointer fields are omitted from the request.
type CreateRequest struct {
	// UserID maps to wire param "user_id".
	UserID *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r CreateRequest) ToParams() url.Values {
	p := url.Values{}
	if r.UserID != nil {
		p.Set("user_id", (*r.UserID))
	}
	return p
}

// GetAuthRequest holds optional parameters for GetAuth.
// Nil pointer fields are omitted from the request.
type GetAuthRequest struct {
	// UserID maps to wire param "user_id".
	UserID *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r GetAuthRequest) ToParams() url.Values {
	p := url.Values{}
	if r.UserID != nil {
		p.Set("user_id", (*r.UserID))
	}
	return p
}
