// Code generated by fsgen. DO NOT EDIT.
package profile

import "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"

// Suppress unused import when all fields use string type.
var _ = types.APIInt(0)

// Profile is a generated response type for the profile package.
type Profile struct {
	// AuthSecret — OAuth1 token secret
	AuthSecret string `json:"auth_secret"`
	// AuthToken — OAuth1 token
	AuthToken string `json:"auth_token"`
	// BirthdayDate — Birthday as days-since-epoch
	BirthdayDate *types.APIDaysEpoch `json:"birthday_date,omitempty"`
	// CurrentHeightCm — Height in centimetres
	CurrentHeightCm *types.APIFloat `json:"current_height_cm,omitempty"`
	// CurrentWeightKg — Current weight in kilograms
	CurrentWeightKg *types.APIFloat `json:"current_weight_kg,omitempty"`
	// Gender — m or f
	Gender *string `json:"gender,omitempty"`
	// GoalWeightKg — Goal weight in kilograms
	GoalWeightKg *types.APIFloat `json:"goal_weight_kg,omitempty"`
	// UserID — Application-assigned user identifier
	UserID *string `json:"user_id,omitempty"`
}

// ProfileAuth is a generated response type for the profile package.
type ProfileAuth struct {
	// AuthSecret — OAuth1 token secret for the user
	AuthSecret string `json:"auth_secret"`
	// AuthToken — OAuth1 token for the user
	AuthToken string `json:"auth_token"`
	// ProfileID — Platform-assigned profile identifier
	ProfileID *string `json:"profile_id,omitempty"`
}
