// Code generated by fsgen. DO NOT EDIT.
package profile

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client"
)

// _ suppresses unused import for packages where all methods use request structs.
var _ = url.Values{}

// Service provides typed access to the profile FatSecret API namespace.
type Service interface {
	// Create calls POST /rest/profile. Auth: oauth1_signed.
	Create(ctx context.Context, req CreateRequest) (ProfileAuth, error)
	// Get calls GET /rest/profile/v1. Auth: oauth1_delegated.
	Get(ctx context.Context) (Profile, error)
	// GetAuth calls GET /rest/profile/get-auth/v1. Auth: oauth1_signed.
	GetAuth(ctx context.Context, req GetAuthRequest) (ProfileAuth, error)
}

type service struct{ c client.Client }

// New returns a Service bound to the given low-level client.
func New(c client.Client) Service { return &service{c: c} }

// Create implements Service.Create.
func (s *service) Create(ctx context.Context, req CreateRequest) (ProfileAuth, error) {
	var zero ProfileAuth
	params := req.ToParams()
	creq := &client.Request{
		Method: "POST",
		Path:   "/rest/profile",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["profile"]
	if !ok {
		return zero, fmt.Errorf("profile.Create: response missing key %q", "profile")
	}
	var result ProfileAuth
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("profile.Create: unmarshal: %w", err)
	}
	return result, nil
}

// Get implements Service.Get.
func (s *service) Get(ctx context.Context) (Profile, error) {
	var zero Profile
	params := url.Values{}
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/profile/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["profile"]
	if !ok {
		return zero, fmt.Errorf("profile.Get: response missing key %q", "profile")
	}
	var result Profile
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("profile.Get: unmarshal: %w", err)
	}
	return result, nil
}

// GetAuth implements Service.GetAuth.
func (s *service) GetAuth(ctx context.Context, req GetAuthRequest) (ProfileAuth, error) {
	var zero ProfileAuth
	params := req.ToParams()
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/profile/get-auth/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["profile"]
	if !ok {
		return zero, fmt.Errorf("profile.GetAuth: response missing key %q", "profile")
	}
	var result ProfileAuth
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("profile.GetAuth: unmarshal: %w", err)
	}
	return result, nil
}
