// Code generated by fsgen. DO NOT EDIT.
package profile_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	profile "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/api/profile"
	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client/mock"
)

// Suppress unused imports for packages where only compile-only tests are generated.
var (
	_ = context.Background
	_ = http.HandlerFunc(nil)
	_ = httptest.NewServer
	_ = strings.HasPrefix
	_ = mock.NewClient
)

// TestSmoke_profile_Create verifies Create dispatches correctly and unmarshals the smoke fixture.
func TestSmoke_profile_Create(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/rest/profile") {
			t.Errorf("unexpected path %s, want prefix %s", r.URL.Path, "/rest/profile")
		}
		if r.Method != "POST" {
			t.Errorf("unexpected method %s, want POST", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{\"profile\":{\"auth_token\":\"abc123\",\"auth_secret\":\"xyz789\"}}"))
	}))
	defer srv.Close()
	svc := profile.New(mock.NewClient(srv.URL))
	_, err := svc.Create(context.Background(), profile.CreateRequest{})
	if err != nil {
		t.Fatalf("Create returned error: %v", err)
	}
}

// TestSmoke_profile_Get verifies Get dispatches correctly and unmarshals the smoke fixture.
func TestSmoke_profile_Get(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/rest/profile/v1") {
			t.Errorf("unexpected path %s, want prefix %s", r.URL.Path, "/rest/profile/v1")
		}
		if r.Method != "GET" {
			t.Errorf("unexpected method %s, want GET", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{\"profile\":{\"auth_token\":\"abc123\",\"auth_secret\":\"xyz789\",\"user_id\":\"user42\"}}"))
	}))
	defer srv.Close()
	svc := profile.New(mock.NewClient(srv.URL))
	_, err := svc.Get(context.Background())
	if err != nil {
		t.Fatalf("Get returned error: %v", err)
	}
}

// TestSmoke_profile_GetAuth verifies GetAuth dispatches correctly and unmarshals the smoke fixture.
func TestSmoke_profile_GetAuth(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/rest/profile/get-auth/v1") {
			t.Errorf("unexpected path %s, want prefix %s", r.URL.Path, "/rest/profile/get-auth/v1")
		}
		if r.Method != "GET" {
			t.Errorf("unexpected method %s, want GET", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{\"profile\":{\"auth_token\":\"abc123\",\"auth_secret\":\"xyz789\"}}"))
	}))
	defer srv.Close()
	svc := profile.New(mock.NewClient(srv.URL))
	_, err := svc.GetAuth(context.Background(), profile.GetAuthRequest{})
	if err != nil {
		t.Fatalf("GetAuth returned error: %v", err)
	}
}
