// Code generated by fsgen. DO NOT EDIT.
package food_sub_categories

import "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"

// Suppress unused import when all fields use string type.
var _ = types.APIInt(0)

// FoodSubCategoriesResult is a generated response type for the food_sub_categories package.
type FoodSubCategoriesResult struct {
	// FoodSubCategory — Food sub-category name list
	FoodSubCategory types.FlexSlice[string] `json:"food_sub_category,omitempty"`
}
