// Code generated by fsgen. DO NOT EDIT.
package food_sub_categories_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	food_sub_categories "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/api/food_sub_categories"
	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client/mock"
)

// Suppress unused imports for packages where only compile-only tests are generated.
var (
	_ = context.Background
	_ = http.HandlerFunc(nil)
	_ = httptest.NewServer
	_ = strings.HasPrefix
	_ = mock.NewClient
)

// TestSmoke_food_sub_categories_GetAllCompiles verifies the interface and request struct compile.
func TestSmoke_food_sub_categories_GetAllCompiles(t *testing.T) {
	var _ food_sub_categories.Service = food_sub_categories.New(nil)
	_ = food_sub_categories.GetAllRequest{}
}
