// Code generated by fsgen. DO NOT EDIT.
package food_entries

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"
	"time"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"
)

// Suppress unused imports for packages that may not be needed for all param types.
var (
	_ = fmt.Sprintf
	_ = json.Marshal
	_ = strconv.FormatFloat
	_ = time.UTC
	_ = types.APIInt(0)
	_ = url.Values{}
)

// CopyRequest holds optional parameters for Copy.
// Nil pointer fields are omitted from the request.
type CopyRequest struct {
	// FromDate maps to wire param "from_date" (required).
	FromDate *types.APIDaysEpoch
	// ToDate maps to wire param "to_date" (required).
	ToDate *types.APIDaysEpoch
	// Meal maps to wire param "meal". Constraint: enum=breakfast,lunch,dinner,other.
	Meal *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r CopyRequest) ToParams() url.Values {
	p := url.Values{}
	if r.FromDate != nil {
		p.Set("from_date", func() string {
			t := time.Time((*r.FromDate))
			days := int64(t.Sub(time.Date(1970, 1, 1, 0, 0, 0, 0, time.UTC)) / (24 * time.Hour))
			return fmt.Sprintf("%d", days)
		}())
	}
	if r.ToDate != nil {
		p.Set("to_date", func() string {
			t := time.Time((*r.ToDate))
			days := int64(t.Sub(time.Date(1970, 1, 1, 0, 0, 0, 0, time.UTC)) / (24 * time.Hour))
			return fmt.Sprintf("%d", days)
		}())
	}
	if r.Meal != nil {
		p.Set("meal", (*r.Meal))
	}
	return p
}

// CreateRequest holds optional parameters for Create.
// Nil pointer fields are omitted from the request.
type CreateRequest struct {
	// FoodID maps to wire param "food_id" (required).
	FoodID *types.APIInt
	// FoodEntryName maps to wire param "food_entry_name" (required).
	FoodEntryName *string
	// ServingID maps to wire param "serving_id" (required).
	ServingID *types.APIInt
	// NumberOfUnits maps to wire param "number_of_units" (required).
	NumberOfUnits *types.APIFloat
	// Meal maps to wire param "meal" (required). Constraint: enum=breakfast,lunch,dinner,other.
	Meal *string
	// Date maps to wire param "date" (required).
	Date *types.APIDaysEpoch
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r CreateRequest) ToParams() url.Values {
	p := url.Values{}
	if r.FoodID != nil {
		p.Set("food_id", fmt.Sprintf("%d", int64((*r.FoodID))))
	}
	if r.FoodEntryName != nil {
		p.Set("food_entry_name", (*r.FoodEntryName))
	}
	if r.ServingID != nil {
		p.Set("serving_id", fmt.Sprintf("%d", int64((*r.ServingID))))
	}
	if r.NumberOfUnits != nil {
		p.Set("number_of_units", strconv.FormatFloat(float64((*r.NumberOfUnits)), 'f', -1, 64))
	}
	if r.Meal != nil {
		p.Set("meal", (*r.Meal))
	}
	if r.Date != nil {
		p.Set("date", func() string {
			t := time.Time((*r.Date))
			days := int64(t.Sub(time.Date(1970, 1, 1, 0, 0, 0, 0, time.UTC)) / (24 * time.Hour))
			return fmt.Sprintf("%d", days)
		}())
	}
	return p
}

// DeleteRequest holds optional parameters for Delete.
// Nil pointer fields are omitted from the request.
type DeleteRequest struct {
	// FoodEntryID maps to wire param "food_entry_id" (required).
	FoodEntryID *types.APIInt
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r DeleteRequest) ToParams() url.Values {
	p := url.Values{}
	if r.FoodEntryID != nil {
		p.Set("food_entry_id", fmt.Sprintf("%d", int64((*r.FoodEntryID))))
	}
	return p
}

// EditRequest holds optional parameters for Edit.
// Nil pointer fields are omitted from the request.
type EditRequest struct {
	// FoodEntryID maps to wire param "food_entry_id" (required).
	FoodEntryID *types.APIInt
	// FoodEntryName maps to wire param "food_entry_name".
	FoodEntryName *string
	// ServingID maps to wire param "serving_id".
	ServingID *types.APIInt
	// NumberOfUnits maps to wire param "number_of_units".
	NumberOfUnits *types.APIFloat
	// Meal maps to wire param "meal". Constraint: enum=breakfast,lunch,dinner,other.
	Meal *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r EditRequest) ToParams() url.Values {
	p := url.Values{}
	if r.FoodEntryID != nil {
		p.Set("food_entry_id", fmt.Sprintf("%d", int64((*r.FoodEntryID))))
	}
	if r.FoodEntryName != nil {
		p.Set("food_entry_name", (*r.FoodEntryName))
	}
	if r.ServingID != nil {
		p.Set("serving_id", fmt.Sprintf("%d", int64((*r.ServingID))))
	}
	if r.NumberOfUnits != nil {
		p.Set("number_of_units", strconv.FormatFloat(float64((*r.NumberOfUnits)), 'f', -1, 64))
	}
	if r.Meal != nil {
		p.Set("meal", (*r.Meal))
	}
	return p
}

// GetRequest holds optional parameters for Get.
// Nil pointer fields are omitted from the request.
type GetRequest struct {
	// Date maps to wire param "date".
	Date *types.APIDaysEpoch
	// FoodEntryID maps to wire param "food_entry_id".
	FoodEntryID *types.APIInt
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r GetRequest) ToParams() url.Values {
	p := url.Values{}
	if r.Date != nil {
		p.Set("date", func() string {
			t := time.Time((*r.Date))
			days := int64(t.Sub(time.Date(1970, 1, 1, 0, 0, 0, 0, time.UTC)) / (24 * time.Hour))
			return fmt.Sprintf("%d", days)
		}())
	}
	if r.FoodEntryID != nil {
		p.Set("food_entry_id", fmt.Sprintf("%d", int64((*r.FoodEntryID))))
	}
	return p
}

// GetMonthRequest holds optional parameters for GetMonth.
// Nil pointer fields are omitted from the request.
type GetMonthRequest struct {
	// Date maps to wire param "date".
	Date *types.APIDaysEpoch
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r GetMonthRequest) ToParams() url.Values {
	p := url.Values{}
	if r.Date != nil {
		p.Set("date", func() string {
			t := time.Time((*r.Date))
			days := int64(t.Sub(time.Date(1970, 1, 1, 0, 0, 0, 0, time.UTC)) / (24 * time.Hour))
			return fmt.Sprintf("%d", days)
		}())
	}
	return p
}
