// Code generated by fsgen. DO NOT EDIT.
package food_entries

import "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"

// Suppress unused import when all fields use string type.
var _ = types.APIInt(0)

// FoodDayEntry is a generated response type for the food_entries package.
type FoodDayEntry struct {
	// Calories — Total calories for the day
	Calories *types.APIFloat `json:"calories,omitempty"`
	// Carbohydrate — Total carbohydrate in grams
	Carbohydrate *types.APIFloat `json:"carbohydrate,omitempty"`
	// DateInt — Days since 1970-01-01
	DateInt types.APIDaysEpoch `json:"date_int"`
	// Fat — Total fat in grams
	Fat *types.APIFloat `json:"fat,omitempty"`
	// Protein — Total protein in grams
	Protein *types.APIFloat `json:"protein,omitempty"`
}

// FoodEntriesResult is a generated response type for the food_entries package.
type FoodEntriesResult struct {
	// FoodEntry — Diary entries; absent when none recorded
	FoodEntry types.FlexSlice[FoodEntry] `json:"food_entry,omitempty"`
}

// FoodEntry is a generated response type for the food_entries package.
type FoodEntry struct {
	// Calories — Calories for this entry
	Calories types.APIFloat `json:"calories"`
	// Carbohydrate — Carbohydrate in grams
	Carbohydrate *types.APIFloat `json:"carbohydrate,omitempty"`
	// DateInt — Days since 1970-01-01
	DateInt types.APIDaysEpoch `json:"date_int"`
	// Fat — Fat in grams
	Fat *types.APIFloat `json:"fat,omitempty"`
	// FoodEntryID — Unique diary entry identifier
	FoodEntryID types.APIInt `json:"food_entry_id"`
	// FoodEntryName — Name of the food as logged
	FoodEntryName string `json:"food_entry_name"`
	// Meal — Meal slot: Breakfast, Lunch, Dinner, or Other
	Meal string `json:"meal"`
	// NumberOfUnits — Number of servings consumed
	NumberOfUnits types.APIFloat `json:"number_of_units"`
	// Protein — Protein in grams
	Protein *types.APIFloat `json:"protein,omitempty"`
	// ServingID — Serving used for this entry
	ServingID types.APIInt `json:"serving_id"`
}

// FoodMonthResult is a generated response type for the food_entries package.
type FoodMonthResult struct {
	// Day — Per-day entry aggregates
	Day types.FlexSlice[FoodDayEntry] `json:"day,omitempty"`
	// Month — Month number string
	Month string `json:"month"`
}

// SuccessResult is a generated response type for the food_entries package.
type SuccessResult struct {
	// Success — 1 on success
	Success types.APIInt `json:"success"`
}
