// Code generated by fsgen. DO NOT EDIT.
package food_entries

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client"
)

// _ suppresses unused import for packages where all methods use request structs.
var _ = url.Values{}

// Service provides typed access to the food_entries FatSecret API namespace.
type Service interface {
	// Copy calls POST /rest/food-entries/copy/v1. Auth: oauth1_delegated.
	Copy(ctx context.Context, req CopyRequest) (SuccessResult, error)
	// Create calls POST /rest/food-entry/v1. Auth: oauth1_delegated.
	Create(ctx context.Context, req CreateRequest) (FoodEntriesResult, error)
	// Delete calls DELETE /rest/food-entry/v1. Auth: oauth1_delegated.
	Delete(ctx context.Context, req DeleteRequest) (SuccessResult, error)
	// Edit calls PUT /rest/food-entry/v1. Auth: oauth1_delegated.
	Edit(ctx context.Context, req EditRequest) (SuccessResult, error)
	// Get calls GET /rest/food-entries/v2. Auth: oauth1_delegated.
	Get(ctx context.Context, req GetRequest) (FoodEntriesResult, error)
	// GetMonth calls GET /rest/food-entries/get-month/v2. Auth: oauth1_delegated.
	GetMonth(ctx context.Context, req GetMonthRequest) (FoodMonthResult, error)
}

type service struct{ c client.Client }

// New returns a Service bound to the given low-level client.
func New(c client.Client) Service { return &service{c: c} }

// Copy implements Service.Copy.
func (s *service) Copy(ctx context.Context, req CopyRequest) (SuccessResult, error) {
	var zero SuccessResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "POST",
		Path:   "/rest/food-entries/copy/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["success"]
	if !ok {
		return zero, fmt.Errorf("food_entries.Copy: response missing key %q", "success")
	}
	var result SuccessResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("food_entries.Copy: unmarshal: %w", err)
	}
	return result, nil
}

// Create implements Service.Create.
func (s *service) Create(ctx context.Context, req CreateRequest) (FoodEntriesResult, error) {
	var zero FoodEntriesResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "POST",
		Path:   "/rest/food-entry/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["food_entries"]
	if !ok {
		return zero, fmt.Errorf("food_entries.Create: response missing key %q", "food_entries")
	}
	var result FoodEntriesResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("food_entries.Create: unmarshal: %w", err)
	}
	return result, nil
}

// Delete implements Service.Delete.
func (s *service) Delete(ctx context.Context, req DeleteRequest) (SuccessResult, error) {
	var zero SuccessResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "DELETE",
		Path:   "/rest/food-entry/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["success"]
	if !ok {
		return zero, fmt.Errorf("food_entries.Delete: response missing key %q", "success")
	}
	var result SuccessResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("food_entries.Delete: unmarshal: %w", err)
	}
	return result, nil
}

// Edit implements Service.Edit.
func (s *service) Edit(ctx context.Context, req EditRequest) (SuccessResult, error) {
	var zero SuccessResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "PUT",
		Path:   "/rest/food-entry/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["success"]
	if !ok {
		return zero, fmt.Errorf("food_entries.Edit: response missing key %q", "success")
	}
	var result SuccessResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("food_entries.Edit: unmarshal: %w", err)
	}
	return result, nil
}

// Get implements Service.Get.
func (s *service) Get(ctx context.Context, req GetRequest) (FoodEntriesResult, error) {
	var zero FoodEntriesResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/food-entries/v2",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["food_entries"]
	if !ok {
		return zero, fmt.Errorf("food_entries.Get: response missing key %q", "food_entries")
	}
	var result FoodEntriesResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("food_entries.Get: unmarshal: %w", err)
	}
	return result, nil
}

// GetMonth implements Service.GetMonth.
func (s *service) GetMonth(ctx context.Context, req GetMonthRequest) (FoodMonthResult, error) {
	var zero FoodMonthResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/food-entries/get-month/v2",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["month"]
	if !ok {
		return zero, fmt.Errorf("food_entries.GetMonth: response missing key %q", "month")
	}
	var result FoodMonthResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("food_entries.GetMonth: unmarshal: %w", err)
	}
	return result, nil
}
