// Code generated by fsgen. DO NOT EDIT.
package food_entries_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	food_entries "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/api/food_entries"
	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client/mock"
)

// Suppress unused imports for packages where only compile-only tests are generated.
var (
	_ = context.Background
	_ = http.HandlerFunc(nil)
	_ = httptest.NewServer
	_ = strings.HasPrefix
	_ = mock.NewClient
)

// TestSmoke_food_entries_CopyCompiles verifies the interface and request struct compile.
func TestSmoke_food_entries_CopyCompiles(t *testing.T) {
	var _ food_entries.Service = food_entries.New(nil)
	_ = food_entries.CopyRequest{}
}

// TestSmoke_food_entries_CreateCompiles verifies the interface and request struct compile.
func TestSmoke_food_entries_CreateCompiles(t *testing.T) {
	var _ food_entries.Service = food_entries.New(nil)
	_ = food_entries.CreateRequest{}
}

// TestSmoke_food_entries_DeleteCompiles verifies the interface and request struct compile.
func TestSmoke_food_entries_DeleteCompiles(t *testing.T) {
	var _ food_entries.Service = food_entries.New(nil)
	_ = food_entries.DeleteRequest{}
}

// TestSmoke_food_entries_EditCompiles verifies the interface and request struct compile.
func TestSmoke_food_entries_EditCompiles(t *testing.T) {
	var _ food_entries.Service = food_entries.New(nil)
	_ = food_entries.EditRequest{}
}

// TestSmoke_food_entries_Get verifies Get dispatches correctly and unmarshals the smoke fixture.
func TestSmoke_food_entries_Get(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/rest/food-entries/v2") {
			t.Errorf("unexpected path %s, want prefix %s", r.URL.Path, "/rest/food-entries/v2")
		}
		if r.Method != "GET" {
			t.Errorf("unexpected method %s, want GET", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{\"food_entries\":{\"food_entry\":[{\"food_entry_id\":\"1111111\",\"date_int\":\"14289\",\"food_entry_name\":\"Chicken Breast\",\"serving_id\":\"11\",\"number_of_units\":\"1.000\",\"meal\":\"Lunch\",\"calories\":\"195\"}]}}"))
	}))
	defer srv.Close()
	svc := food_entries.New(mock.NewClient(srv.URL))
	_, err := svc.Get(context.Background(), food_entries.GetRequest{})
	if err != nil {
		t.Fatalf("Get returned error: %v", err)
	}
}

// TestSmoke_food_entries_GetMonth verifies GetMonth dispatches correctly and unmarshals the smoke fixture.
func TestSmoke_food_entries_GetMonth(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/rest/food-entries/get-month/v2") {
			t.Errorf("unexpected path %s, want prefix %s", r.URL.Path, "/rest/food-entries/get-month/v2")
		}
		if r.Method != "GET" {
			t.Errorf("unexpected method %s, want GET", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{\"month\":{\"day\":[{\"date_int\":\"14289\",\"calories\":\"1500\",\"carbohydrate\":\"150\",\"protein\":\"100\",\"fat\":\"50\"}]}}"))
	}))
	defer srv.Close()
	svc := food_entries.New(mock.NewClient(srv.URL))
	_, err := svc.GetMonth(context.Background(), food_entries.GetMonthRequest{})
	if err != nil {
		t.Fatalf("GetMonth returned error: %v", err)
	}
}
