// Code generated by fsgen. DO NOT EDIT.
package feedback

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"
	"time"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"
)

// Suppress unused imports for packages that may not be needed for all param types.
var (
	_ = fmt.Sprintf
	_ = json.Marshal
	_ = strconv.FormatFloat
	_ = time.UTC
	_ = types.APIInt(0)
	_ = url.Values{}
)

// SubmitRequest holds optional parameters for Submit.
// Nil pointer fields are omitted from the request.
type SubmitRequest struct {
	// IssueTypeID maps to wire param "issue_type_id" (required).
	IssueTypeID *types.APIInt
	// ExternalID maps to wire param "external_id" (required).
	ExternalID *string
	// Barcode maps to wire param "barcode".
	Barcode *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r SubmitRequest) ToParams() url.Values {
	p := url.Values{}
	if r.IssueTypeID != nil {
		p.Set("issue_type_id", fmt.Sprintf("%d", int64((*r.IssueTypeID))))
	}
	if r.ExternalID != nil {
		p.Set("external_id", (*r.ExternalID))
	}
	if r.Barcode != nil {
		p.Set("barcode", (*r.Barcode))
	}
	return p
}
