// Code generated by fsgen. DO NOT EDIT.
package feedback

import "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"

// Suppress unused import when all fields use string type.
var _ = types.APIInt(0)

// FeedbackResponse is a generated response type for the feedback package.
type FeedbackResponse struct {
	// TrackingID — Submission tracking identifier
	TrackingID string `json:"tracking_id"`
	// UploadURLBack — Pre-signed URL to upload back-of-pack image
	UploadURLBack *string `json:"upload_url_back,omitempty"`
	// UploadURLFront — Pre-signed URL to upload front-of-pack image
	UploadURLFront *string `json:"upload_url_front,omitempty"`
	// UploadURLIngredients — Pre-signed URL to upload ingredients image
	UploadURLIngredients *string `json:"upload_url_ingredients,omitempty"`
	// UploadURLNutrition — Pre-signed URL to upload nutrition panel image
	UploadURLNutrition *string `json:"upload_url_nutrition,omitempty"`
}
