// Code generated by fsgen. DO NOT EDIT.
package feedback

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client"
)

// _ suppresses unused import for packages where all methods use request structs.
var _ = url.Values{}

// Service provides typed access to the feedback FatSecret API namespace.
type Service interface {
	// Submit calls POST /rest/feedback/v1. Auth: client_credentials. Scope: feedback.
	Submit(ctx context.Context, req SubmitRequest) (FeedbackResponse, error)
}

type service struct{ c client.Client }

// New returns a Service bound to the given low-level client.
func New(c client.Client) Service { return &service{c: c} }

// Submit implements Service.Submit.
func (s *service) Submit(ctx context.Context, req SubmitRequest) (FeedbackResponse, error) {
	var zero FeedbackResponse
	params := req.ToParams()
	creq := &client.Request{
		Method: "POST",
		Path:   "/rest/feedback/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["feedback"]
	if !ok {
		return zero, fmt.Errorf("feedback.Submit: response missing key %q", "feedback")
	}
	var result FeedbackResponse
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("feedback.Submit: unmarshal: %w", err)
	}
	return result, nil
}
