// Code generated by fsgen. DO NOT EDIT.
package feedback_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	feedback "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/api/feedback"
	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client/mock"
)

// Suppress unused imports for packages where only compile-only tests are generated.
var (
	_ = context.Background
	_ = http.HandlerFunc(nil)
	_ = httptest.NewServer
	_ = strings.HasPrefix
	_ = mock.NewClient
)

// TestSmoke_feedback_SubmitCompiles verifies the interface and request struct compile.
func TestSmoke_feedback_SubmitCompiles(t *testing.T) {
	var _ feedback.Service = feedback.New(nil)
	_ = feedback.SubmitRequest{}
}
