// Code generated by fsgen. DO NOT EDIT.
package saved_meals

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"
	"time"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"
)

// Suppress unused imports for packages that may not be needed for all param types.
var (
	_ = fmt.Sprintf
	_ = json.Marshal
	_ = strconv.FormatFloat
	_ = time.UTC
	_ = types.APIInt(0)
	_ = url.Values{}
)

// AddItemRequest holds optional parameters for AddItem.
// Nil pointer fields are omitted from the request.
type AddItemRequest struct {
	// SavedMealID maps to wire param "saved_meal_id" (required).
	SavedMealID *types.APIInt
	// FoodID maps to wire param "food_id" (required).
	FoodID *types.APIInt
	// SavedMealItemName maps to wire param "saved_meal_item_name" (required).
	SavedMealItemName *string
	// ServingID maps to wire param "serving_id" (required).
	ServingID *types.APIInt
	// NumberOfUnits maps to wire param "number_of_units" (required).
	NumberOfUnits *types.APIFloat
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r AddItemRequest) ToParams() url.Values {
	p := url.Values{}
	if r.SavedMealID != nil {
		p.Set("saved_meal_id", fmt.Sprintf("%d", int64((*r.SavedMealID))))
	}
	if r.FoodID != nil {
		p.Set("food_id", fmt.Sprintf("%d", int64((*r.FoodID))))
	}
	if r.SavedMealItemName != nil {
		p.Set("saved_meal_item_name", (*r.SavedMealItemName))
	}
	if r.ServingID != nil {
		p.Set("serving_id", fmt.Sprintf("%d", int64((*r.ServingID))))
	}
	if r.NumberOfUnits != nil {
		p.Set("number_of_units", strconv.FormatFloat(float64((*r.NumberOfUnits)), 'f', -1, 64))
	}
	return p
}

// CreateRequest holds optional parameters for Create.
// Nil pointer fields are omitted from the request.
type CreateRequest struct {
	// SavedMealName maps to wire param "saved_meal_name" (required).
	SavedMealName *string
	// SavedMealDescription maps to wire param "saved_meal_description".
	SavedMealDescription *string
	// Meals maps to wire param "meals". Constraint: enum=breakfast,lunch,dinner,other.
	Meals *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r CreateRequest) ToParams() url.Values {
	p := url.Values{}
	if r.SavedMealName != nil {
		p.Set("saved_meal_name", (*r.SavedMealName))
	}
	if r.SavedMealDescription != nil {
		p.Set("saved_meal_description", (*r.SavedMealDescription))
	}
	if r.Meals != nil {
		p.Set("meals", (*r.Meals))
	}
	return p
}

// DeleteRequest holds optional parameters for Delete.
// Nil pointer fields are omitted from the request.
type DeleteRequest struct {
	// SavedMealID maps to wire param "saved_meal_id" (required).
	SavedMealID *types.APIInt
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r DeleteRequest) ToParams() url.Values {
	p := url.Values{}
	if r.SavedMealID != nil {
		p.Set("saved_meal_id", fmt.Sprintf("%d", int64((*r.SavedMealID))))
	}
	return p
}

// DeleteItemRequest holds optional parameters for DeleteItem.
// Nil pointer fields are omitted from the request.
type DeleteItemRequest struct {
	// SavedMealItemID maps to wire param "saved_meal_item_id" (required).
	SavedMealItemID *types.APIInt
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r DeleteItemRequest) ToParams() url.Values {
	p := url.Values{}
	if r.SavedMealItemID != nil {
		p.Set("saved_meal_item_id", fmt.Sprintf("%d", int64((*r.SavedMealItemID))))
	}
	return p
}

// EditRequest holds optional parameters for Edit.
// Nil pointer fields are omitted from the request.
type EditRequest struct {
	// SavedMealID maps to wire param "saved_meal_id" (required).
	SavedMealID *types.APIInt
	// SavedMealName maps to wire param "saved_meal_name".
	SavedMealName *string
	// SavedMealDescription maps to wire param "saved_meal_description".
	SavedMealDescription *string
	// Meals maps to wire param "meals". Constraint: enum=breakfast,lunch,dinner,other.
	Meals *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r EditRequest) ToParams() url.Values {
	p := url.Values{}
	if r.SavedMealID != nil {
		p.Set("saved_meal_id", fmt.Sprintf("%d", int64((*r.SavedMealID))))
	}
	if r.SavedMealName != nil {
		p.Set("saved_meal_name", (*r.SavedMealName))
	}
	if r.SavedMealDescription != nil {
		p.Set("saved_meal_description", (*r.SavedMealDescription))
	}
	if r.Meals != nil {
		p.Set("meals", (*r.Meals))
	}
	return p
}

// EditItemRequest holds optional parameters for EditItem.
// Nil pointer fields are omitted from the request.
type EditItemRequest struct {
	// SavedMealItemID maps to wire param "saved_meal_item_id" (required).
	SavedMealItemID *types.APIInt
	// ServingID maps to wire param "serving_id".
	ServingID *types.APIInt
	// NumberOfUnits maps to wire param "number_of_units".
	NumberOfUnits *types.APIFloat
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r EditItemRequest) ToParams() url.Values {
	p := url.Values{}
	if r.SavedMealItemID != nil {
		p.Set("saved_meal_item_id", fmt.Sprintf("%d", int64((*r.SavedMealItemID))))
	}
	if r.ServingID != nil {
		p.Set("serving_id", fmt.Sprintf("%d", int64((*r.ServingID))))
	}
	if r.NumberOfUnits != nil {
		p.Set("number_of_units", strconv.FormatFloat(float64((*r.NumberOfUnits)), 'f', -1, 64))
	}
	return p
}

// ListRequest holds optional parameters for List.
// Nil pointer fields are omitted from the request.
type ListRequest struct {
	// Meal maps to wire param "meal". Constraint: enum=breakfast,lunch,dinner,other.
	Meal *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r ListRequest) ToParams() url.Values {
	p := url.Values{}
	if r.Meal != nil {
		p.Set("meal", (*r.Meal))
	}
	return p
}

// ListItemsRequest holds optional parameters for ListItems.
// Nil pointer fields are omitted from the request.
type ListItemsRequest struct {
	// SavedMealID maps to wire param "saved_meal_id" (required).
	SavedMealID *types.APIInt
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r ListItemsRequest) ToParams() url.Values {
	p := url.Values{}
	if r.SavedMealID != nil {
		p.Set("saved_meal_id", fmt.Sprintf("%d", int64((*r.SavedMealID))))
	}
	return p
}
