// Code generated by fsgen. DO NOT EDIT.
package saved_meals

import "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"

// Suppress unused import when all fields use string type.
var _ = types.APIInt(0)

// SavedMeal is a generated response type for the saved_meals package.
type SavedMeal struct {
	// Meals — Meal slot association: Breakfast, Lunch, Dinner, or Other
	Meals *string `json:"meals,omitempty"`
	// SavedMealDescription — Optional description
	SavedMealDescription *string `json:"saved_meal_description,omitempty"`
	// SavedMealID — Unique saved meal identifier
	SavedMealID types.APIInt `json:"saved_meal_id"`
	// SavedMealName — Meal display name
	SavedMealName string `json:"saved_meal_name"`
}

// SavedMealCreateResult is a generated response type for the saved_meals package.
type SavedMealCreateResult struct {
	// SavedMealID — Identifier of the newly created saved meal
	SavedMealID types.APIInt `json:"saved_meal_id"`
}

// SavedMealItem is a generated response type for the saved_meals package.
type SavedMealItem struct {
	// FoodEntryName — Food name as saved
	FoodEntryName string `json:"food_entry_name"`
	// FoodID — Food identifier
	FoodID types.APIInt `json:"food_id"`
	// Meal — Meal slot
	Meal string `json:"meal"`
	// NumberOfUnits — Number of servings
	NumberOfUnits types.APIFloat `json:"number_of_units"`
	// SavedMealItemID — Unique saved meal item identifier
	SavedMealItemID types.APIInt `json:"saved_meal_item_id"`
	// ServingID — Serving identifier
	ServingID types.APIInt `json:"serving_id"`
}

// SavedMealItemCreateResult is a generated response type for the saved_meals package.
type SavedMealItemCreateResult struct {
	// SavedMealItemID — Identifier of the newly created saved meal item
	SavedMealItemID types.APIInt `json:"saved_meal_item_id"`
}

// SavedMealItemsResult is a generated response type for the saved_meals package.
type SavedMealItemsResult struct {
	// SavedMealItem — Saved meal item list
	SavedMealItem types.FlexSlice[SavedMealItem] `json:"saved_meal_item,omitempty"`
}

// SavedMealsResult is a generated response type for the saved_meals package.
type SavedMealsResult struct {
	// SavedMeal — Saved meal list
	SavedMeal types.FlexSlice[SavedMeal] `json:"saved_meal,omitempty"`
}

// SuccessResult is a generated response type for the saved_meals package.
type SuccessResult struct {
	// Success — 1 on success
	Success types.APIInt `json:"success"`
}
