// Code generated by fsgen. DO NOT EDIT.
package saved_meals

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client"
)

// _ suppresses unused import for packages where all methods use request structs.
var _ = url.Values{}

// Service provides typed access to the saved_meals FatSecret API namespace.
type Service interface {
	// AddItem calls POST /rest/saved-meal-item/v1. Auth: oauth1_delegated.
	AddItem(ctx context.Context, req AddItemRequest) (SavedMealItemCreateResult, error)
	// Create calls POST /rest/saved-meal/v1. Auth: oauth1_delegated.
	Create(ctx context.Context, req CreateRequest) (SavedMealCreateResult, error)
	// Delete calls DELETE /rest/saved-meal/v1. Auth: oauth1_delegated.
	Delete(ctx context.Context, req DeleteRequest) (SuccessResult, error)
	// DeleteItem calls DELETE /rest/saved-meal-item/v1. Auth: oauth1_delegated.
	DeleteItem(ctx context.Context, req DeleteItemRequest) (SuccessResult, error)
	// Edit calls PUT /rest/saved-meal/v1. Auth: oauth1_delegated.
	Edit(ctx context.Context, req EditRequest) (SuccessResult, error)
	// EditItem calls PUT /rest/saved-meal-item/v1. Auth: oauth1_delegated.
	EditItem(ctx context.Context, req EditItemRequest) (SuccessResult, error)
	// List calls GET /rest/saved-meals/v2. Auth: oauth1_delegated.
	List(ctx context.Context, req ListRequest) (SavedMealsResult, error)
	// ListItems calls GET /rest/saved-meal-items/v2. Auth: oauth1_delegated.
	ListItems(ctx context.Context, req ListItemsRequest) (SavedMealItemsResult, error)
}

type service struct{ c client.Client }

// New returns a Service bound to the given low-level client.
func New(c client.Client) Service { return &service{c: c} }

// AddItem implements Service.AddItem.
func (s *service) AddItem(ctx context.Context, req AddItemRequest) (SavedMealItemCreateResult, error) {
	var zero SavedMealItemCreateResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "POST",
		Path:   "/rest/saved-meal-item/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["saved_meal_item"]
	if !ok {
		return zero, fmt.Errorf("saved_meals.AddItem: response missing key %q", "saved_meal_item")
	}
	var result SavedMealItemCreateResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("saved_meals.AddItem: unmarshal: %w", err)
	}
	return result, nil
}

// Create implements Service.Create.
func (s *service) Create(ctx context.Context, req CreateRequest) (SavedMealCreateResult, error) {
	var zero SavedMealCreateResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "POST",
		Path:   "/rest/saved-meal/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["saved_meal"]
	if !ok {
		return zero, fmt.Errorf("saved_meals.Create: response missing key %q", "saved_meal")
	}
	var result SavedMealCreateResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("saved_meals.Create: unmarshal: %w", err)
	}
	return result, nil
}

// Delete implements Service.Delete.
func (s *service) Delete(ctx context.Context, req DeleteRequest) (SuccessResult, error) {
	var zero SuccessResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "DELETE",
		Path:   "/rest/saved-meal/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["success"]
	if !ok {
		return zero, fmt.Errorf("saved_meals.Delete: response missing key %q", "success")
	}
	var result SuccessResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("saved_meals.Delete: unmarshal: %w", err)
	}
	return result, nil
}

// DeleteItem implements Service.DeleteItem.
func (s *service) DeleteItem(ctx context.Context, req DeleteItemRequest) (SuccessResult, error) {
	var zero SuccessResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "DELETE",
		Path:   "/rest/saved-meal-item/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["success"]
	if !ok {
		return zero, fmt.Errorf("saved_meals.DeleteItem: response missing key %q", "success")
	}
	var result SuccessResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("saved_meals.DeleteItem: unmarshal: %w", err)
	}
	return result, nil
}

// Edit implements Service.Edit.
func (s *service) Edit(ctx context.Context, req EditRequest) (SuccessResult, error) {
	var zero SuccessResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "PUT",
		Path:   "/rest/saved-meal/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["success"]
	if !ok {
		return zero, fmt.Errorf("saved_meals.Edit: response missing key %q", "success")
	}
	var result SuccessResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("saved_meals.Edit: unmarshal: %w", err)
	}
	return result, nil
}

// EditItem implements Service.EditItem.
func (s *service) EditItem(ctx context.Context, req EditItemRequest) (SuccessResult, error) {
	var zero SuccessResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "PUT",
		Path:   "/rest/saved-meal-item/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["success"]
	if !ok {
		return zero, fmt.Errorf("saved_meals.EditItem: response missing key %q", "success")
	}
	var result SuccessResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("saved_meals.EditItem: unmarshal: %w", err)
	}
	return result, nil
}

// List implements Service.List.
func (s *service) List(ctx context.Context, req ListRequest) (SavedMealsResult, error) {
	var zero SavedMealsResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/saved-meals/v2",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["saved_meals"]
	if !ok {
		return zero, fmt.Errorf("saved_meals.List: response missing key %q", "saved_meals")
	}
	var result SavedMealsResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("saved_meals.List: unmarshal: %w", err)
	}
	return result, nil
}

// ListItems implements Service.ListItems.
func (s *service) ListItems(ctx context.Context, req ListItemsRequest) (SavedMealItemsResult, error) {
	var zero SavedMealItemsResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/saved-meal-items/v2",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["saved_meal_items"]
	if !ok {
		return zero, fmt.Errorf("saved_meals.ListItems: response missing key %q", "saved_meal_items")
	}
	var result SavedMealItemsResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("saved_meals.ListItems: unmarshal: %w", err)
	}
	return result, nil
}
