// Code generated by fsgen. DO NOT EDIT.
package saved_meals_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	saved_meals "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/api/saved_meals"
	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client/mock"
)

// Suppress unused imports for packages where only compile-only tests are generated.
var (
	_ = context.Background
	_ = http.HandlerFunc(nil)
	_ = httptest.NewServer
	_ = strings.HasPrefix
	_ = mock.NewClient
)

// TestSmoke_saved_meals_AddItemCompiles verifies the interface and request struct compile.
func TestSmoke_saved_meals_AddItemCompiles(t *testing.T) {
	var _ saved_meals.Service = saved_meals.New(nil)
	_ = saved_meals.AddItemRequest{}
}

// TestSmoke_saved_meals_CreateCompiles verifies the interface and request struct compile.
func TestSmoke_saved_meals_CreateCompiles(t *testing.T) {
	var _ saved_meals.Service = saved_meals.New(nil)
	_ = saved_meals.CreateRequest{}
}

// TestSmoke_saved_meals_DeleteCompiles verifies the interface and request struct compile.
func TestSmoke_saved_meals_DeleteCompiles(t *testing.T) {
	var _ saved_meals.Service = saved_meals.New(nil)
	_ = saved_meals.DeleteRequest{}
}

// TestSmoke_saved_meals_DeleteItemCompiles verifies the interface and request struct compile.
func TestSmoke_saved_meals_DeleteItemCompiles(t *testing.T) {
	var _ saved_meals.Service = saved_meals.New(nil)
	_ = saved_meals.DeleteItemRequest{}
}

// TestSmoke_saved_meals_EditCompiles verifies the interface and request struct compile.
func TestSmoke_saved_meals_EditCompiles(t *testing.T) {
	var _ saved_meals.Service = saved_meals.New(nil)
	_ = saved_meals.EditRequest{}
}

// TestSmoke_saved_meals_EditItemCompiles verifies the interface and request struct compile.
func TestSmoke_saved_meals_EditItemCompiles(t *testing.T) {
	var _ saved_meals.Service = saved_meals.New(nil)
	_ = saved_meals.EditItemRequest{}
}

// TestSmoke_saved_meals_List verifies List dispatches correctly and unmarshals the smoke fixture.
func TestSmoke_saved_meals_List(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/rest/saved-meals/v2") {
			t.Errorf("unexpected path %s, want prefix %s", r.URL.Path, "/rest/saved-meals/v2")
		}
		if r.Method != "GET" {
			t.Errorf("unexpected method %s, want GET", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{\"saved_meals\":{\"saved_meal\":[{\"saved_meal_id\":\"1\",\"saved_meal_name\":\"My Lunch\"}]}}"))
	}))
	defer srv.Close()
	svc := saved_meals.New(mock.NewClient(srv.URL))
	_, err := svc.List(context.Background(), saved_meals.ListRequest{})
	if err != nil {
		t.Fatalf("List returned error: %v", err)
	}
}

// TestSmoke_saved_meals_ListItemsCompiles verifies the interface and request struct compile.
func TestSmoke_saved_meals_ListItemsCompiles(t *testing.T) {
	var _ saved_meals.Service = saved_meals.New(nil)
	_ = saved_meals.ListItemsRequest{}
}
