// Code generated by fsgen. DO NOT EDIT.
package native

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"
	"time"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"
)

// Suppress unused imports for packages that may not be needed for all param types.
var (
	_ = fmt.Sprintf
	_ = json.Marshal
	_ = strconv.FormatFloat
	_ = time.UTC
	_ = types.APIInt(0)
	_ = url.Values{}
)

// ProcessRequest holds optional parameters for Process.
// Nil pointer fields are omitted from the request.
type ProcessRequest struct {
	// UserInput maps to wire param "user_input" (required).
	UserInput *string
	// IncludeFoodData maps to wire param "include_food_data".
	IncludeFoodData *types.APIBool
	// Region maps to wire param "region".
	Region *string
	// Language maps to wire param "language".
	Language *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r ProcessRequest) ToParams() url.Values {
	p := url.Values{}
	if r.UserInput != nil {
		p.Set("user_input", (*r.UserInput))
	}
	if r.IncludeFoodData != nil {
		p.Set("include_food_data", func() string {
			if bool((*r.IncludeFoodData)) {
				return "1"
			}
			return "0"
		}())
	}
	if r.Region != nil {
		p.Set("region", (*r.Region))
	}
	if r.Language != nil {
		p.Set("language", (*r.Language))
	}
	return p
}

// ToJSONBody encodes set fields into the JSON request body this endpoint
// requires. Values keep their JSON-native types — booleans stay booleans —
// because the endpoint rejects a form-encoded body with the generic error
// code 1 and does not coerce stringified values.
func (r ProcessRequest) ToJSONBody() ([]byte, error) {
	m := map[string]any{}
	if r.UserInput != nil {
		m["user_input"] = (*r.UserInput)
	}
	if r.IncludeFoodData != nil {
		m["include_food_data"] = bool((*r.IncludeFoodData))
	}
	if r.Region != nil {
		m["region"] = (*r.Region)
	}
	if r.Language != nil {
		m["language"] = (*r.Language)
	}
	return json.Marshal(m)
}

// RecognizeRequest holds optional parameters for Recognize.
// Nil pointer fields are omitted from the request.
type RecognizeRequest struct {
	// ImageB64 maps to wire param "image_b64" (required).
	ImageB64 *string
	// IncludeFoodData maps to wire param "include_food_data".
	IncludeFoodData *types.APIBool
	// Region maps to wire param "region".
	Region *string
	// Language maps to wire param "language".
	Language *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r RecognizeRequest) ToParams() url.Values {
	p := url.Values{}
	if r.ImageB64 != nil {
		p.Set("image_b64", (*r.ImageB64))
	}
	if r.IncludeFoodData != nil {
		p.Set("include_food_data", func() string {
			if bool((*r.IncludeFoodData)) {
				return "1"
			}
			return "0"
		}())
	}
	if r.Region != nil {
		p.Set("region", (*r.Region))
	}
	if r.Language != nil {
		p.Set("language", (*r.Language))
	}
	return p
}

// ToJSONBody encodes set fields into the JSON request body this endpoint
// requires. Values keep their JSON-native types — booleans stay booleans —
// because the endpoint rejects a form-encoded body with the generic error
// code 1 and does not coerce stringified values.
func (r RecognizeRequest) ToJSONBody() ([]byte, error) {
	m := map[string]any{}
	if r.ImageB64 != nil {
		m["image_b64"] = (*r.ImageB64)
	}
	if r.IncludeFoodData != nil {
		m["include_food_data"] = bool((*r.IncludeFoodData))
	}
	if r.Region != nil {
		m["region"] = (*r.Region)
	}
	if r.Language != nil {
		m["language"] = (*r.Language)
	}
	return json.Marshal(m)
}
