// Code generated by fsgen. DO NOT EDIT.
package native

import "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"

// Suppress unused import when all fields use string type.
var _ = types.APIInt(0)

// NLPFoodResponse is a generated response type for the native package.
type NLPFoodResponse struct {
	// FoodEntryName — Recognized food name
	FoodEntryName string `json:"food_entry_name"`
	// FoodID — Matched food identifier
	FoodID types.APIInt `json:"food_id"`
	// Servings — Serving suggestions
	Servings types.FlexSlice[Serving] `json:"servings,omitempty"`
}

// Serving is a generated response type for the native package.
type Serving struct {
	// AddedSugars — Added sugars in grams; v4+ only
	AddedSugars *types.APIFloat `json:"added_sugars,omitempty"`
	// Calcium — Calcium in mg
	Calcium *types.APIFloat `json:"calcium,omitempty"`
	// Calories — Energy in kcal
	Calories types.APIFloat `json:"calories"`
	// Carbohydrate — Total carbohydrate in grams
	Carbohydrate types.APIFloat `json:"carbohydrate"`
	// Cholesterol — Cholesterol in mg
	Cholesterol *types.APIFloat `json:"cholesterol,omitempty"`
	// Fat — Total fat in grams
	Fat types.APIFloat `json:"fat"`
	// Fiber — Dietary fiber in grams
	Fiber *types.APIFloat `json:"fiber,omitempty"`
	// Iron — Iron in mg
	Iron *types.APIFloat `json:"iron,omitempty"`
	// IsDefault — Whether this is the default serving; Premier tier only
	IsDefault *types.APIBool `json:"is_default,omitempty"`
	// MeasurementDescription — Unit description matching number_of_units
	MeasurementDescription string `json:"measurement_description"`
	// MetricServingAmount — Amount in metric units; absent if no metric equivalent
	MetricServingAmount *types.APIFloat `json:"metric_serving_amount,omitempty"`
	// MetricServingUnit — Metric unit (g, ml, etc.)
	MetricServingUnit *string `json:"metric_serving_unit,omitempty"`
	// MonounsaturatedFat — Monounsaturated fat in grams
	MonounsaturatedFat *types.APIFloat `json:"monounsaturated_fat,omitempty"`
	// NumberOfUnits — Number of serving units
	NumberOfUnits types.APIFloat `json:"number_of_units"`
	// PolyunsaturatedFat — Polyunsaturated fat in grams
	PolyunsaturatedFat *types.APIFloat `json:"polyunsaturated_fat,omitempty"`
	// Potassium — Potassium in mg
	Potassium *types.APIFloat `json:"potassium,omitempty"`
	// Protein — Protein in grams
	Protein types.APIFloat `json:"protein"`
	// SaturatedFat — Saturated fat in grams
	SaturatedFat *types.APIFloat `json:"saturated_fat,omitempty"`
	// ServingDescription — Human-readable serving description (e.g. '1 cup')
	ServingDescription string `json:"serving_description"`
	// ServingID — Unique serving identifier
	ServingID types.APIInt `json:"serving_id"`
	// ServingURL — FatSecret URL for the serving
	ServingURL string `json:"serving_url"`
	// Sodium — Sodium in mg
	Sodium *types.APIFloat `json:"sodium,omitempty"`
	// Sugar — Total sugars in grams
	Sugar *types.APIFloat `json:"sugar,omitempty"`
	// TransFat — Trans fat in grams
	TransFat *types.APIFloat `json:"trans_fat,omitempty"`
	// VitaminA — Vitamin A in mcg
	VitaminA *types.APIFloat `json:"vitamin_a,omitempty"`
	// VitaminC — Vitamin C in mg
	VitaminC *types.APIFloat `json:"vitamin_c,omitempty"`
	// VitaminD — Vitamin D in mcg; v4+ only
	VitaminD *types.APIFloat `json:"vitamin_d,omitempty"`
}
