// Code generated by fsgen. DO NOT EDIT.
package native

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client"
)

// _ suppresses unused import for packages where all methods use request structs.
var _ = url.Values{}

// Service provides typed access to the native FatSecret API namespace.
type Service interface {
	// Process calls POST /rest/natural-language-processing/v1. Auth: client_credentials. Scope: nlp.
	Process(ctx context.Context, req ProcessRequest) (NLPFoodResponse, error)
	// Recognize calls POST /rest/image-recognition/v2. Auth: client_credentials. Scope: image-recognition.
	Recognize(ctx context.Context, req RecognizeRequest) (NLPFoodResponse, error)
}

type service struct{ c client.Client }

// New returns a Service bound to the given low-level client.
func New(c client.Client) Service { return &service{c: c} }

// Process implements Service.Process.
func (s *service) Process(ctx context.Context, req ProcessRequest) (NLPFoodResponse, error) {
	var zero NLPFoodResponse
	params := req.ToParams()
	creq := &client.Request{
		Method: "POST",
		Path:   "/rest/natural-language-processing/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["food_response"]
	if !ok {
		return zero, fmt.Errorf("native.Process: response missing key %q", "food_response")
	}
	var result NLPFoodResponse
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("native.Process: unmarshal: %w", err)
	}
	return result, nil
}

// Recognize implements Service.Recognize.
func (s *service) Recognize(ctx context.Context, req RecognizeRequest) (NLPFoodResponse, error) {
	var zero NLPFoodResponse
	params := req.ToParams()
	creq := &client.Request{
		Method: "POST",
		Path:   "/rest/image-recognition/v2",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["food_response"]
	if !ok {
		return zero, fmt.Errorf("native.Recognize: response missing key %q", "food_response")
	}
	var result NLPFoodResponse
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("native.Recognize: unmarshal: %w", err)
	}
	return result, nil
}
