// Code generated by fsgen. DO NOT EDIT.
package native_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	native "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/api/native"
	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client/mock"
)

// Suppress unused imports for packages where only compile-only tests are generated.
var (
	_ = context.Background
	_ = http.HandlerFunc(nil)
	_ = httptest.NewServer
	_ = strings.HasPrefix
	_ = mock.NewClient
)

// TestSmoke_native_ProcessCompiles verifies the interface and request struct compile.
func TestSmoke_native_ProcessCompiles(t *testing.T) {
	var _ native.Service = native.New(nil)
	_ = native.ProcessRequest{}
}

// TestSmoke_native_RecognizeCompiles verifies the interface and request struct compile.
func TestSmoke_native_RecognizeCompiles(t *testing.T) {
	var _ native.Service = native.New(nil)
	_ = native.RecognizeRequest{}
}
