// Code generated by fsgen. DO NOT EDIT.
package food_brands

import "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"

// Suppress unused import when all fields use string type.
var _ = types.APIInt(0)

// FoodBrand is a generated response type for the food_brands package.
type FoodBrand struct {
	// BrandID — Unique brand identifier
	BrandID types.APIInt `json:"brand_id"`
	// BrandName — Brand display name
	BrandName string `json:"brand_name"`
	// BrandType — manufacturer, restaurant, or supermarket
	BrandType *string `json:"brand_type,omitempty"`
}

// FoodBrandsResult is a generated response type for the food_brands package.
type FoodBrandsResult struct {
	// Brand — Brand list
	Brand types.FlexSlice[FoodBrand] `json:"brand,omitempty"`
}
