// Code generated by fsgen. DO NOT EDIT.
package food_brands_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	food_brands "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/api/food_brands"
	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client/mock"
)

// Suppress unused imports for packages where only compile-only tests are generated.
var (
	_ = context.Background
	_ = http.HandlerFunc(nil)
	_ = httptest.NewServer
	_ = strings.HasPrefix
	_ = mock.NewClient
)

// TestSmoke_food_brands_GetAllCompiles verifies the interface and request struct compile.
func TestSmoke_food_brands_GetAllCompiles(t *testing.T) {
	var _ food_brands.Service = food_brands.New(nil)
	_ = food_brands.GetAllRequest{}
}
