package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/cmd/fsgen/ir"
)

// repoRoot returns the absolute path to the repository root by walking up from
// the test binary's working directory until go.mod is found.
func repoRoot(t *testing.T) string {
	t.Helper()
	dir, err := filepath.Abs(".")
	if err != nil {
		t.Fatalf("filepath.Abs: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("could not find repository root (go.mod not found)")
		}
		dir = parent
	}
}

// TestPipeline_Integration runs the full pipeline against the real spec and
// verifies the expected structural output.
func TestPipeline_Integration(t *testing.T) {
	root := repoRoot(t)
	specPath := filepath.Join(root, "spec", "fatsecret.yaml")
	overridesPath := filepath.Join(root, "spec", "name_overrides.yaml")
	outDir := t.TempDir()

	if err := Pipeline(specPath, overridesPath, outDir, false); err != nil {
		t.Fatalf("Pipeline: %v", err)
	}

	// Verify at least one namespace package directory was created under pkg/api/.
	apiDir := filepath.Join(outDir, "pkg", "api")
	entries, err := os.ReadDir(apiDir)
	if err != nil {
		t.Fatalf("expected pkg/api/ to exist: %v", err)
	}
	if len(entries) == 0 {
		t.Fatal("expected at least one namespace directory under pkg/api/")
	}

	// Find a service.go in any namespace dir and assert generated header.
	found := false
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		svcPath := filepath.Join(apiDir, e.Name(), "service.go")
		data, err := os.ReadFile(svcPath)
		if err != nil {
			continue
		}
		// Line 1 must be the generated header.
		firstLine := strings.SplitN(string(data), "\n", 2)[0]
		if firstLine != "// Code generated by fsgen. DO NOT EDIT." {
			t.Errorf("service.go in %q: line 1 = %q, want generated header", e.Name(), firstLine)
		}
		found = true
		break
	}
	if !found {
		t.Error("no service.go found under any namespace directory")
	}

	// Verify compatibility matrix was written.
	matrixPath := filepath.Join(outDir, "pkg", "compatibility", "matrix.go")
	matrixData, err := os.ReadFile(matrixPath)
	if err != nil {
		t.Fatalf("expected matrix.go to exist: %v", err)
	}
	if !strings.Contains(string(matrixData), "var Matrix = []Entry{") {
		t.Error("matrix.go missing expected Matrix variable declaration")
	}
}

// TestPipeline_Idempotent verifies that running the pipeline twice produces
// byte-identical output files.
func TestPipeline_Idempotent(t *testing.T) {
	root := repoRoot(t)
	specPath := filepath.Join(root, "spec", "fatsecret.yaml")
	overridesPath := filepath.Join(root, "spec", "name_overrides.yaml")

	out1 := t.TempDir()
	out2 := t.TempDir()

	if err := Pipeline(specPath, overridesPath, out1, false); err != nil {
		t.Fatalf("Pipeline run 1: %v", err)
	}
	if err := Pipeline(specPath, overridesPath, out2, false); err != nil {
		t.Fatalf("Pipeline run 2: %v", err)
	}

	// Walk out1 and compare every file against out2.
	err := filepath.Walk(out1, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		rel, _ := filepath.Rel(out1, path)
		b1, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		b2, err := os.ReadFile(filepath.Join(out2, rel))
		if err != nil {
			t.Errorf("file %q missing from second run: %v", rel, err)
			return nil
		}
		if !bytes.Equal(b1, b2) {
			t.Errorf("file %q differs between run 1 and run 2 (not idempotent)", rel)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("Walk error: %v", err)
	}
}

// TestPipeline_DryRun verifies that --dry-run prints file paths but writes nothing.
func TestPipeline_DryRun(t *testing.T) {
	root := repoRoot(t)
	specPath := filepath.Join(root, "spec", "fatsecret.yaml")
	overridesPath := filepath.Join(root, "spec", "name_overrides.yaml")
	outDir := t.TempDir()

	if err := Pipeline(specPath, overridesPath, outDir, true); err != nil {
		t.Fatalf("Pipeline dry-run: %v", err)
	}

	// outDir must remain empty (no files written).
	entries, err := os.ReadDir(outDir)
	if err != nil {
		t.Fatalf("ReadDir: %v", err)
	}
	if len(entries) != 0 {
		t.Errorf("dry-run wrote %d entries to outDir, expected none", len(entries))
	}
}

// TestPipeline_MissingSpec verifies that a non-existent spec path returns an error.
func TestPipeline_MissingSpec(t *testing.T) {
	err := Pipeline("/nonexistent/path/fatsecret.yaml", "/nonexistent/overrides.yaml", t.TempDir(), false)
	if err == nil {
		t.Fatal("expected error for missing spec, got nil")
	}
	if !strings.Contains(err.Error(), "parse spec") {
		t.Errorf("expected error to mention 'parse spec'; got: %v", err)
	}
}

// TestPipeline_InvalidSpec verifies that a spec with invalid YAML returns an error.
func TestPipeline_InvalidSpec(t *testing.T) {
	dir := t.TempDir()
	specPath := filepath.Join(dir, "bad.yaml")
	if err := os.WriteFile(specPath, []byte("{{invalid yaml{{"), 0o644); err != nil {
		t.Fatal(err)
	}
	err := Pipeline(specPath, filepath.Join(dir, "overrides.yaml"), t.TempDir(), false)
	if err == nil {
		t.Fatal("expected error for invalid spec YAML, got nil")
	}
}

// TestPipeline_OverridesMissing verifies that Pipeline does not treat a
// missing overrides file as a file-read error; it proceeds (possibly failing
// later at the build step if the spec requires overrides to resolve duplicates,
// which is a spec-validity concern, not an overrides-file concern).
func TestPipeline_OverridesMissing(t *testing.T) {
	root := repoRoot(t)
	specPath := filepath.Join(root, "spec", "fatsecret.yaml")
	overridesPath := filepath.Join(root, "spec", "name_overrides.yaml")
	outDir := t.TempDir()

	// Use real overrides; confirm the happy path succeeds.
	if err := Pipeline(specPath, overridesPath, outDir, true); err != nil {
		t.Fatalf("Pipeline (dry-run): %v", err)
	}

	// Now verify that a non-existent overrides file is NOT treated as a read error.
	// The ir.ParseOverrides contract returns nil for os.IsNotExist.
	// We cannot use the real spec here (it requires overrides); use a minimal spec
	// that has no duplicates to confirm the nil-overrides path.
	dir := t.TempDir()
	minSpec := filepath.Join(dir, "min.yaml")
	minYAML := `version: "1"
types:
  R:
    kind: object
methods:
  - namespace: foods
    name: search
    version: 3
    http_verb: GET
    rest_path: /rest/foods/search/v3
    auth_tier: client_credentials
    response_type: R
`
	if err := os.WriteFile(minSpec, []byte(minYAML), 0o644); err != nil {
		t.Fatal(err)
	}
	missingOverrides := filepath.Join(t.TempDir(), "nonexistent_overrides.yaml")
	if err := Pipeline(minSpec, missingOverrides, t.TempDir(), false); err != nil {
		t.Fatalf("Pipeline with missing overrides file: %v", err)
	}
}

// TestPipeline_WriteFile_MkdirError verifies that writeFile propagates mkdir errors.
// This exercises the error path where the parent directory cannot be created.
func TestPipeline_WriteFile_ReadOnlyParent(t *testing.T) {
	dir := t.TempDir()
	// Create a regular file where a directory is needed, so MkdirAll fails.
	blocker := filepath.Join(dir, "pkg")
	if err := os.WriteFile(blocker, []byte("blocker"), 0o444); err != nil {
		t.Fatal(err)
	}

	root := repoRoot(t)
	specPath := filepath.Join(root, "spec", "fatsecret.yaml")
	overridesPath := filepath.Join(root, "spec", "name_overrides.yaml")

	err := Pipeline(specPath, overridesPath, dir, false)
	if err == nil {
		t.Fatal("expected error when output directory structure is blocked, got nil")
	}
}

// TestRenderAll_EmptyNamespaces verifies that RenderAll on an empty slice
// returns an empty slice without error.
func TestRenderAll_EmptyNamespaces(t *testing.T) {
	files, err := RenderAll(nil)
	if err != nil {
		t.Fatalf("RenderAll(nil): %v", err)
	}
	if len(files) != 0 {
		t.Errorf("expected 0 files, got %d", len(files))
	}
}

// TestIntsLiteral verifies the helper that renders []int as a Go literal.
func TestIntsLiteral(t *testing.T) {
	cases := []struct {
		in   []int
		want string
	}{
		{nil, "[]int{}"},
		{[]int{}, "[]int{}"},
		{[]int{1}, "[]int{1}"},
		{[]int{1, 2, 3}, "[]int{1, 2, 3}"},
	}
	for _, tc := range cases {
		got := intsLiteral(tc.in)
		if got != tc.want {
			t.Errorf("intsLiteral(%v) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

// TestAppendUnique verifies the deduplication helper.
func TestAppendUnique(t *testing.T) {
	got := appendUnique([]int{1, 2}, 2, 3, 3, 4)
	want := []int{1, 2, 3, 4}
	if len(got) != len(want) {
		t.Fatalf("appendUnique len=%d, want %d; got %v", len(got), len(want), got)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("appendUnique[%d]=%d, want %d", i, got[i], want[i])
		}
	}
}

// TestGoFieldName exercises the PascalCase conversion used in templates.
func TestGoFieldName(t *testing.T) {
	cases := []struct {
		in   string
		want string
	}{
		{"food_id", "FoodID"},
		{"food_url", "FoodURL"},
		{"serving_description", "ServingDescription"},
		{"food_name", "FoodName"},
		{"nlp_result", "NLPResult"},
		{"ids", "IDs"},
		{"simple", "Simple"},
	}
	for _, tc := range cases {
		got := goFieldName(tc.in)
		if got != tc.want {
			t.Errorf("goFieldName(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

// TestGoType verifies all known type mappings.
func TestGoType(t *testing.T) {
	cases := []struct {
		in   string
		want string
	}{
		{"string", "string"},
		{"APIInt", "types.APIInt"},
		{"APIFloat", "types.APIFloat"},
		{"APIBool", "types.APIBool"},
		{"APITernary", "types.APITernary"},
		{"APIDaysEpoch", "types.APIDaysEpoch"},
		{"FlexSlice[Food]", "types.FlexSlice[Food]"},
		{"FlexSlice[string]", "types.FlexSlice[string]"},
		{"Food", "Food"}, // named type returned as-is
	}
	for _, tc := range cases {
		got := goType(tc.in)
		if got != tc.want {
			t.Errorf("goType(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

// TestGoResponseFieldType verifies pointer/non-pointer logic for struct fields.
func TestGoResponseFieldType(t *testing.T) {
	cases := []struct {
		typeName string
		required bool
		want     string
	}{
		{"string", true, "string"},
		{"string", false, "*string"},
		{"APIInt", true, "types.APIInt"},
		{"APIInt", false, "*types.APIInt"},
		{"FlexSlice[Food]", true, "types.FlexSlice[Food]"},
		{"FlexSlice[Food]", false, "types.FlexSlice[Food]"}, // FlexSlice never gets pointer
		{"Food", true, "Food"},
		{"Food", false, "Food"}, // named object type: no pointer (zero value fine)
	}
	for _, tc := range cases {
		got := goResponseFieldType(tc.typeName, tc.required)
		if got != tc.want {
			t.Errorf("goResponseFieldType(%q, %v) = %q, want %q", tc.typeName, tc.required, got, tc.want)
		}
	}
}

// TestEncodeParam verifies encoding expressions for all param types.
func TestEncodeParam(t *testing.T) {
	cases := []struct {
		typeName string
		expr     string
		wantSub  string // substring expected in result
	}{
		{"string", "v", "v"},
		{"APIInt", "v", "int64(v)"},
		{"APIFloat", "v", "FormatFloat"},
		{"APIBool", "v", "bool(v)"},
		{"APITernary", "v", "int8(v)"},
		{"APIDaysEpoch", "v", "time.Time(v)"},
		{"UnknownType", "v", `fmt.Sprintf("%v", v)`},
	}
	for _, tc := range cases {
		got := encodeParam(tc.typeName, tc.expr)
		if !strings.Contains(got, tc.wantSub) {
			t.Errorf("encodeParam(%q, %q) = %q, want substring %q", tc.typeName, tc.expr, got, tc.wantSub)
		}
	}
}

// TestRenderCompatibility_Structure verifies that RenderCompatibility produces
// valid matrix.go content with the expected structure.
func TestRenderCompatibility_Structure(t *testing.T) {
	root := repoRoot(t)
	specPath := filepath.Join(root, "spec", "fatsecret.yaml")

	spec, err := ir.ParseSpec(specPath)
	if err != nil {
		t.Fatalf("ir.ParseSpec: %v", err)
	}

	rf, err := RenderCompatibility(spec)
	if err != nil {
		t.Fatalf("RenderCompatibility: %v", err)
	}
	if rf.RelPath != "pkg/compatibility/matrix.go" {
		t.Errorf("RelPath = %q, want %q", rf.RelPath, "pkg/compatibility/matrix.go")
	}
	content := string(rf.Content)
	for _, want := range []string{
		"// Code generated by fsgen. DO NOT EDIT.",
		"package compatibility",
		"type Entry struct {",
		"var Matrix = []Entry{",
	} {
		if !strings.Contains(content, want) {
			t.Errorf("matrix.go missing expected fragment %q", want)
		}
	}
}

// TestRenderCompatibility_HelperCoverage validates renderer-level helpers and
// serves as a final compilation smoke test.
func TestRenderCompatibility_HelperCoverage(t *testing.T) {
	// pathPrefix is a pass-through; verify it.
	got := pathPrefix("/rest/foods/search/v3")
	if got != "/rest/foods/search/v3" {
		t.Errorf("pathPrefix = %q, want %q", got, "/rest/foods/search/v3")
	}

	// isScalarType coverage.
	scalars := []string{"string", "APIInt", "APIFloat", "APIBool", "APITernary", "APIDaysEpoch"}
	for _, s := range scalars {
		if !isScalarType(s) {
			t.Errorf("isScalarType(%q) = false, want true", s)
		}
	}
	if isScalarType("Food") {
		t.Error("isScalarType(Food) = true, want false")
	}
}
