package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"sort"
	"strings"
	"text/template"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/cmd/fsgen/ir"
)

//go:embed templates/service.go.tmpl
var serviceTmpl string

//go:embed templates/request.go.tmpl
var requestTmpl string

//go:embed templates/response.go.tmpl
var responseTmpl string

//go:embed templates/smoke_test.go.tmpl
var smokeTestTmpl string

// RenderedFile is one output file produced by the renderer.
type RenderedFile struct {
	// RelPath is the path relative to outDir (e.g. "pkg/api/foods/service.go").
	RelPath string
	// Content is the formatted Go source bytes.
	Content []byte
}

// RenderAll renders all namespace packages into RenderedFile values.
// It does not write to disk; the pipeline layer handles writing.
func RenderAll(namespaces []ir.Namespace) ([]RenderedFile, error) {
	var files []RenderedFile
	for _, ns := range namespaces {
		rendered, err := renderNamespace(ns)
		if err != nil {
			return nil, fmt.Errorf("renderer: namespace %q: %w", ns.PackageName, err)
		}
		files = append(files, rendered...)
	}
	return files, nil
}

// RenderCompatibility renders the pkg/compatibility/matrix.go file.
func RenderCompatibility(spec *ir.Spec) (RenderedFile, error) { //nolint:unparam // error return kept for interface consistency — future validation may return errors
	var buf bytes.Buffer
	buf.WriteString("// Code generated by fsgen. DO NOT EDIT.\n")
	buf.WriteString("package compatibility\n\n")
	buf.WriteString("// Entry describes versioning metadata for one API method.\n")
	buf.WriteString("type Entry struct {\n")
	buf.WriteString("\tNamespace  string\n")
	buf.WriteString("\tName       string\n")
	buf.WriteString("\tVersions   []int\n")
	buf.WriteString("\tDeprecated []int\n")
	buf.WriteString("\tAuthTier   string\n")
	buf.WriteString("\tScope      string\n")
	buf.WriteString("}\n\n")
	buf.WriteString("// Matrix is the complete catalog of all FatSecret API methods known to this client.\n")
	buf.WriteString("var Matrix = []Entry{\n")

	// De-duplicate: one Matrix entry per (namespace, name) containing all versions.
	type key struct{ ns, name string }
	type entry struct {
		k          key
		versions   []int
		deprecated []int
		authTier   string
		scope      string
	}
	seen := make(map[key]*entry)
	var order []key

	for _, m := range spec.Methods {
		k := key{m.Namespace, m.Name}
		if _, ok := seen[k]; !ok {
			seen[k] = &entry{k: k, authTier: m.AuthTier, scope: m.Scope}
			order = append(order, k)
		}
		e := seen[k]
		e.versions = appendUnique(e.versions, m.AllVersions...)
		e.deprecated = appendUnique(e.deprecated, m.DeprecatedVersions...)
	}

	// Sort order for determinism.
	sort.Slice(order, func(i, j int) bool {
		if order[i].ns != order[j].ns {
			return order[i].ns < order[j].ns
		}
		return order[i].name < order[j].name
	})

	for _, k := range order {
		e := seen[k]
		sort.Ints(e.versions)
		sort.Ints(e.deprecated)
		fmt.Fprintf(&buf, "\t{Namespace: %q, Name: %q, Versions: %s, Deprecated: %s, AuthTier: %q, Scope: %q},\n",
			e.k.ns, e.k.name,
			intsLiteral(e.versions),
			intsLiteral(e.deprecated),
			e.authTier, e.scope)
	}
	buf.WriteString("}\n")

	return RenderedFile{
		RelPath: "pkg/compatibility/matrix.go",
		Content: buf.Bytes(),
	}, nil
}

// renderNamespace renders service.go, request.go (if needed), response.go, and
// smoke_test.go for one namespace package.
func renderNamespace(ns ir.Namespace) ([]RenderedFile, error) {
	base := "pkg/api/" + ns.PackageName
	funcMap := buildFuncMap()

	var files []RenderedFile

	// service.go — always emitted.
	svc, err := renderTemplate("service", serviceTmpl, funcMap, ns)
	if err != nil {
		return nil, err
	}
	files = append(files, RenderedFile{RelPath: base + "/service.go", Content: svc})

	// request.go — only when at least one method has a request struct.
	needsReq := false
	for _, m := range ns.Methods {
		if m.HasRequestStruct {
			needsReq = true
			break
		}
	}
	if needsReq {
		req, err := renderTemplate("request", requestTmpl, funcMap, ns)
		if err != nil {
			return nil, err
		}
		files = append(files, RenderedFile{RelPath: base + "/request.go", Content: req})
	}

	// response.go — only when the namespace has non-primitive types.
	if ns.NeedsTypes {
		resp, err := renderTemplate("response", responseTmpl, funcMap, ns)
		if err != nil {
			return nil, err
		}
		files = append(files, RenderedFile{RelPath: base + "/response.go", Content: resp})
	}

	// smoke_test.go — always emitted.
	smoke, err := renderTemplate("smoke_test", smokeTestTmpl, funcMap, ns)
	if err != nil {
		return nil, err
	}
	files = append(files, RenderedFile{RelPath: base + "/smoke_test.go", Content: smoke})

	return files, nil
}

// renderTemplate parses and executes a named template with the given data.
func renderTemplate(name, tmplText string, funcMap template.FuncMap, data any) ([]byte, error) {
	t, err := template.New(name).Funcs(funcMap).Parse(tmplText)
	if err != nil {
		return nil, fmt.Errorf("parse template %q: %w", name, err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("execute template %q: %w", name, err)
	}
	return buf.Bytes(), nil
}

// buildFuncMap returns the template.FuncMap registered for all templates.
func buildFuncMap() template.FuncMap {
	return template.FuncMap{
		"GoFieldName":         goFieldName,
		"GoType":              goType,
		"GoResponseType":      goResponseType,
		"GoResponseFieldType": goResponseFieldType,
		"EncodeParam":         encodeParam,
		"PathPrefix":          pathPrefix,
		"not":                 func(b bool) bool { return !b },
	}
}

// goFieldName converts a snake_case wire name to a PascalCase Go field name,
// applying the acronym table for common abbreviations.
func goFieldName(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool { return r == '_' || r == '.' })
	var sb strings.Builder
	for _, part := range parts {
		sb.WriteString(upperPart(part))
	}
	return sb.String()
}

// acronyms are known abbreviations that should be fully uppercased in Go names.
var acronyms = map[string]string{
	"id":  "ID",
	"ids": "IDs",
	"url": "URL",
	"nlp": "NLP",
}

func upperPart(part string) string {
	if up, ok := acronyms[strings.ToLower(part)]; ok {
		return up
	}
	if len(part) == 0 {
		return ""
	}
	return strings.ToUpper(part[:1]) + part[1:]
}

// goType maps a spec type keyword to the Go type string used in request structs
// (pointer-free, for encoding).
func goType(typeName string) string {
	switch typeName {
	case "string":
		return "string"
	case "APIInt":
		return "types.APIInt"
	case "APIFloat":
		return "types.APIFloat"
	case "APIBool":
		return "types.APIBool"
	case "APITernary":
		return "types.APITernary"
	case "APIDaysEpoch":
		return "types.APIDaysEpoch"
	}
	if strings.HasPrefix(typeName, "FlexSlice[") && strings.HasSuffix(typeName, "]") {
		inner := typeName[len("FlexSlice[") : len(typeName)-1]
		return "types.FlexSlice[" + goResponseType(inner) + "]"
	}
	// Named response type — use as-is (defined in same package).
	return typeName
}

// goResponseType maps a spec type to the Go type used in return positions.
// Same as goType but used for method signatures and response struct fields.
func goResponseType(typeName string) string {
	return goType(typeName)
}

// goResponseFieldType maps a spec type to a struct field type, adding pointer
// when the field is not required.
func goResponseFieldType(typeName string, required bool) string {
	t := goType(typeName)
	if required {
		return t
	}
	// FlexSlice and named object types don't need pointer (zero value is fine).
	if strings.HasPrefix(t, "types.FlexSlice[") || (!strings.HasPrefix(t, "types.") && !isScalarType(typeName)) {
		return t
	}
	return "*" + t
}

func isScalarType(typeName string) bool {
	switch typeName {
	case "string", "APIInt", "APIFloat", "APIBool", "APITernary", "APIDaysEpoch":
		return true
	}
	return false
}

// encodeParam returns a Go expression that converts a dereferenced param value
// to a url.Values-compatible string. The expr is the Go expression for the value.
func encodeParam(typeName, expr string) string {
	switch typeName {
	case "string":
		return expr
	case "APIInt":
		return fmt.Sprintf("fmt.Sprintf(\"%%d\", int64(%s))", expr)
	case "APIFloat":
		return fmt.Sprintf("strconv.FormatFloat(float64(%s), 'f', -1, 64)", expr)
	case "APIBool":
		return fmt.Sprintf("func() string { if bool(%s) { return \"1\" }; return \"0\" }()", expr)
	case "APITernary":
		return fmt.Sprintf("fmt.Sprintf(\"%%d\", int8(%s))", expr)
	case "APIDaysEpoch":
		// APIDaysEpoch is time.Time underneath; encode as days since 1970-01-01.
		return fmt.Sprintf("func() string { t := time.Time(%s); days := int64(t.Sub(time.Date(1970,1,1,0,0,0,0,time.UTC)) / (24 * time.Hour)); return fmt.Sprintf(\"%%d\", days) }()", expr)
	}
	// Fallback: use fmt.Sprintf with %v for named types.
	return fmt.Sprintf("fmt.Sprintf(\"%%v\", %s)", expr)
}

// pathPrefix strips any vN suffix query params to produce the path prefix for smoke test assertions.
func pathPrefix(restPath string) string {
	// Return the path as-is; the smoke test uses HasPrefix which handles query strings.
	return restPath
}

// intsLiteral renders a []int as a Go literal.
func intsLiteral(vals []int) string {
	if len(vals) == 0 {
		return "[]int{}"
	}
	parts := make([]string, len(vals))
	for i, v := range vals {
		parts[i] = fmt.Sprintf("%d", v)
	}
	return "[]int{" + strings.Join(parts, ", ") + "}"
}

// appendUnique appends values to dst if not already present.
func appendUnique(dst []int, vals ...int) []int {
	set := make(map[int]bool, len(dst))
	for _, v := range dst {
		set[v] = true
	}
	for _, v := range vals {
		if !set[v] {
			dst = append(dst, v)
			set[v] = true
		}
	}
	return dst
}
