// Code generated by fsgen. DO NOT EDIT.
package food_categories

import (
	"fmt"
	"net/url"
	"strconv"
	"time"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"
)

// Suppress unused imports for packages that may not be needed for all param types.
var (
	_ = fmt.Sprintf
	_ = strconv.FormatFloat
	_ = time.UTC
	_ = types.APIInt(0)
	_ = url.Values{}
)

// GetAllRequest holds optional parameters for GetAll.
// Nil pointer fields are omitted from the request.
type GetAllRequest struct {
	// Region maps to wire param "region".
	Region *string
	// Language maps to wire param "language".
	Language *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r GetAllRequest) ToParams() url.Values {
	p := url.Values{}
	if r.Region != nil {
		p.Set("region", (*r.Region))
	}
	if r.Language != nil {
		p.Set("language", (*r.Language))
	}
	return p
}
