// Code generated by fsgen. DO NOT EDIT.
package food_categories

import "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"

// Suppress unused import when all fields use string type.
var _ = types.APIInt(0)

// FoodCategoriesResult is a generated response type for the food_categories package.
type FoodCategoriesResult struct {
	// FoodCategory — Food category list
	FoodCategory types.FlexSlice[FoodCategory] `json:"food_category,omitempty"`
}

// FoodCategory is a generated response type for the food_categories package.
type FoodCategory struct {
	// FoodCategoryDescription — Category description
	FoodCategoryDescription *string `json:"food_category_description,omitempty"`
	// FoodCategoryID — Unique category identifier
	FoodCategoryID types.APIInt `json:"food_category_id"`
	// FoodCategoryName — Category display name
	FoodCategoryName string `json:"food_category_name"`
}
