// Code generated by fsgen. DO NOT EDIT.
package food_categories

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client"
)

// _ suppresses unused import for packages where all methods use request structs.
var _ = url.Values{}

// Service provides typed access to the food_categories FatSecret API namespace.
type Service interface {
	// GetAll calls GET /rest/food-categories/v2. Auth: client_credentials. Scope: premier.
	GetAll(ctx context.Context, req GetAllRequest) (FoodCategoriesResult, error)
}

type service struct{ c client.Client }

// New returns a Service bound to the given low-level client.
func New(c client.Client) Service { return &service{c: c} }

// GetAll implements Service.GetAll.
func (s *service) GetAll(ctx context.Context, req GetAllRequest) (FoodCategoriesResult, error) {
	var zero FoodCategoriesResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/food-categories/v2",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["food_categories"]
	if !ok {
		return zero, fmt.Errorf("food_categories.GetAll: response missing key %q", "food_categories")
	}
	var result FoodCategoriesResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("food_categories.GetAll: unmarshal: %w", err)
	}
	return result, nil
}
