// Code generated by fsgen. DO NOT EDIT.
package food_categories_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	food_categories "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/api/food_categories"
	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client/mock"
)

// Suppress unused imports for packages where only compile-only tests are generated.
var (
	_ = context.Background
	_ = http.HandlerFunc(nil)
	_ = httptest.NewServer
	_ = strings.HasPrefix
	_ = mock.NewClient
)

// TestSmoke_food_categories_GetAll verifies GetAll dispatches correctly and unmarshals the smoke fixture.
func TestSmoke_food_categories_GetAll(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/rest/food-categories/v2") {
			t.Errorf("unexpected path %s, want prefix %s", r.URL.Path, "/rest/food-categories/v2")
		}
		if r.Method != "GET" {
			t.Errorf("unexpected method %s, want GET", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{\"food_categories\":{\"food_category\":[{\"food_category_id\":\"1\",\"food_category_name\":\"Baked Products\",\"food_category_description\":\"Breads, muffins, etc.\"}]}}"))
	}))
	defer srv.Close()
	svc := food_categories.New(mock.NewClient(srv.URL))
	_, err := svc.GetAll(context.Background(), food_categories.GetAllRequest{})
	if err != nil {
		t.Fatalf("GetAll returned error: %v", err)
	}
}
