// Code generated by fsgen. DO NOT EDIT.
package exercises

import "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"

// Suppress unused import when all fields use string type.
var _ = types.APIInt(0)

// Exercise is a generated response type for the exercises package.
type Exercise struct {
	// ExerciseID — Unique exercise type identifier
	ExerciseID types.APIInt `json:"exercise_id"`
	// ExerciseName — Exercise display name
	ExerciseName string `json:"exercise_name"`
}

// ExercisesResult is a generated response type for the exercises package.
type ExercisesResult struct {
	// Exercise — Exercise type list
	Exercise types.FlexSlice[Exercise] `json:"exercise,omitempty"`
}
