// Code generated by fsgen. DO NOT EDIT.
package exercises

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client"
)

// _ suppresses unused import for packages where all methods use request structs.
var _ = url.Values{}

// Service provides typed access to the exercises FatSecret API namespace.
type Service interface {
	// Get calls GET /rest/exercises/v2. Auth: client_credentials. Scope: basic.
	Get(ctx context.Context, req GetRequest) (ExercisesResult, error)
}

type service struct{ c client.Client }

// New returns a Service bound to the given low-level client.
func New(c client.Client) Service { return &service{c: c} }

// Get implements Service.Get.
func (s *service) Get(ctx context.Context, req GetRequest) (ExercisesResult, error) {
	var zero ExercisesResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/exercises/v2",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["exercises"]
	if !ok {
		return zero, fmt.Errorf("exercises.Get: response missing key %q", "exercises")
	}
	var result ExercisesResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("exercises.Get: unmarshal: %w", err)
	}
	return result, nil
}
