// Code generated by fsgen. DO NOT EDIT.
package exercises_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	exercises "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/api/exercises"
	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client/mock"
)

// Suppress unused imports for packages where only compile-only tests are generated.
var (
	_ = context.Background
	_ = http.HandlerFunc(nil)
	_ = httptest.NewServer
	_ = strings.HasPrefix
	_ = mock.NewClient
)

// TestSmoke_exercises_Get verifies Get dispatches correctly and unmarshals the smoke fixture.
func TestSmoke_exercises_Get(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/rest/exercises/v2") {
			t.Errorf("unexpected path %s, want prefix %s", r.URL.Path, "/rest/exercises/v2")
		}
		if r.Method != "GET" {
			t.Errorf("unexpected method %s, want GET", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{\"exercises\":{\"exercise\":[{\"exercise_id\":\"1\",\"exercise_name\":\"Running\"}]}}"))
	}))
	defer srv.Close()
	svc := exercises.New(mock.NewClient(srv.URL))
	_, err := svc.Get(context.Background(), exercises.GetRequest{})
	if err != nil {
		t.Fatalf("Get returned error: %v", err)
	}
}
