// Code generated by fsgen. DO NOT EDIT.
package foods

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"
	"time"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"
)

// Suppress unused imports for packages that may not be needed for all param types.
var (
	_ = fmt.Sprintf
	_ = json.Marshal
	_ = strconv.FormatFloat
	_ = time.UTC
	_ = types.APIInt(0)
	_ = url.Values{}
)

// AutocompleteRequest holds optional parameters for Autocomplete.
// Nil pointer fields are omitted from the request.
type AutocompleteRequest struct {
	// Expression maps to wire param "expression" (required).
	Expression *string
	// MaxResults maps to wire param "max_results". Constraint: max=10.
	MaxResults *types.APIInt
	// Region maps to wire param "region".
	Region *string
	// Language maps to wire param "language".
	Language *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r AutocompleteRequest) ToParams() url.Values {
	p := url.Values{}
	if r.Expression != nil {
		p.Set("expression", (*r.Expression))
	}
	if r.MaxResults != nil {
		p.Set("max_results", fmt.Sprintf("%d", int64((*r.MaxResults))))
	}
	if r.Region != nil {
		p.Set("region", (*r.Region))
	}
	if r.Language != nil {
		p.Set("language", (*r.Language))
	}
	return p
}

// GetMostEatenRequest holds optional parameters for GetMostEaten.
// Nil pointer fields are omitted from the request.
type GetMostEatenRequest struct {
	// Meal maps to wire param "meal". Constraint: enum=breakfast,lunch,dinner,other.
	Meal *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r GetMostEatenRequest) ToParams() url.Values {
	p := url.Values{}
	if r.Meal != nil {
		p.Set("meal", (*r.Meal))
	}
	return p
}

// GetRecentlyEatenRequest holds optional parameters for GetRecentlyEaten.
// Nil pointer fields are omitted from the request.
type GetRecentlyEatenRequest struct {
	// Meal maps to wire param "meal". Constraint: enum=breakfast,lunch,dinner,other.
	Meal *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r GetRecentlyEatenRequest) ToParams() url.Values {
	p := url.Values{}
	if r.Meal != nil {
		p.Set("meal", (*r.Meal))
	}
	return p
}

// SearchRequest holds optional parameters for Search.
// Nil pointer fields are omitted from the request.
type SearchRequest struct {
	// SearchExpression maps to wire param "search_expression".
	SearchExpression *string
	// PageNumber maps to wire param "page_number".
	PageNumber *types.APIInt
	// MaxResults maps to wire param "max_results". Constraint: max=50.
	MaxResults *types.APIInt
	// FoodType maps to wire param "food_type". Constraint: enum=generic,brand.
	FoodType *string
	// IncludeSubCategories maps to wire param "include_sub_categories" (premier tier only).
	IncludeSubCategories *types.APIBool
	// IncludeFoodImages maps to wire param "include_food_images" (premier tier only).
	IncludeFoodImages *types.APIBool
	// IncludeFoodAttributes maps to wire param "include_food_attributes" (premier tier only).
	IncludeFoodAttributes *types.APIBool
	// FlagDefaultServing maps to wire param "flag_default_serving".
	FlagDefaultServing *types.APIBool
	// Region maps to wire param "region".
	Region *string
	// Language maps to wire param "language".
	Language *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r SearchRequest) ToParams() url.Values {
	p := url.Values{}
	if r.SearchExpression != nil {
		p.Set("search_expression", (*r.SearchExpression))
	}
	if r.PageNumber != nil {
		p.Set("page_number", fmt.Sprintf("%d", int64((*r.PageNumber))))
	}
	if r.MaxResults != nil {
		p.Set("max_results", fmt.Sprintf("%d", int64((*r.MaxResults))))
	}
	if r.FoodType != nil {
		p.Set("food_type", (*r.FoodType))
	}
	if r.IncludeSubCategories != nil {
		p.Set("include_sub_categories", func() string {
			if bool((*r.IncludeSubCategories)) {
				return "1"
			}
			return "0"
		}())
	}
	if r.IncludeFoodImages != nil {
		p.Set("include_food_images", func() string {
			if bool((*r.IncludeFoodImages)) {
				return "1"
			}
			return "0"
		}())
	}
	if r.IncludeFoodAttributes != nil {
		p.Set("include_food_attributes", func() string {
			if bool((*r.IncludeFoodAttributes)) {
				return "1"
			}
			return "0"
		}())
	}
	if r.FlagDefaultServing != nil {
		p.Set("flag_default_serving", func() string {
			if bool((*r.FlagDefaultServing)) {
				return "1"
			}
			return "0"
		}())
	}
	if r.Region != nil {
		p.Set("region", (*r.Region))
	}
	if r.Language != nil {
		p.Set("language", (*r.Language))
	}
	return p
}

// SearchV5Request holds optional parameters for SearchV5.
// Nil pointer fields are omitted from the request.
type SearchV5Request struct {
	// SearchExpression maps to wire param "search_expression".
	SearchExpression *string
	// PageNumber maps to wire param "page_number".
	PageNumber *types.APIInt
	// MaxResults maps to wire param "max_results". Constraint: max=50.
	MaxResults *types.APIInt
	// FoodType maps to wire param "food_type". Constraint: enum=generic,brand.
	FoodType *string
	// IncludeSubCategories maps to wire param "include_sub_categories" (premier tier only).
	IncludeSubCategories *types.APIBool
	// IncludeFoodImages maps to wire param "include_food_images" (premier tier only).
	IncludeFoodImages *types.APIBool
	// IncludeFoodAttributes maps to wire param "include_food_attributes" (premier tier only).
	IncludeFoodAttributes *types.APIBool
	// FlagDefaultServing maps to wire param "flag_default_serving".
	FlagDefaultServing *types.APIBool
	// Region maps to wire param "region".
	Region *string
	// Language maps to wire param "language".
	Language *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r SearchV5Request) ToParams() url.Values {
	p := url.Values{}
	if r.SearchExpression != nil {
		p.Set("search_expression", (*r.SearchExpression))
	}
	if r.PageNumber != nil {
		p.Set("page_number", fmt.Sprintf("%d", int64((*r.PageNumber))))
	}
	if r.MaxResults != nil {
		p.Set("max_results", fmt.Sprintf("%d", int64((*r.MaxResults))))
	}
	if r.FoodType != nil {
		p.Set("food_type", (*r.FoodType))
	}
	if r.IncludeSubCategories != nil {
		p.Set("include_sub_categories", func() string {
			if bool((*r.IncludeSubCategories)) {
				return "1"
			}
			return "0"
		}())
	}
	if r.IncludeFoodImages != nil {
		p.Set("include_food_images", func() string {
			if bool((*r.IncludeFoodImages)) {
				return "1"
			}
			return "0"
		}())
	}
	if r.IncludeFoodAttributes != nil {
		p.Set("include_food_attributes", func() string {
			if bool((*r.IncludeFoodAttributes)) {
				return "1"
			}
			return "0"
		}())
	}
	if r.FlagDefaultServing != nil {
		p.Set("flag_default_serving", func() string {
			if bool((*r.FlagDefaultServing)) {
				return "1"
			}
			return "0"
		}())
	}
	if r.Region != nil {
		p.Set("region", (*r.Region))
	}
	if r.Language != nil {
		p.Set("language", (*r.Language))
	}
	return p
}
