// Code generated by fsgen. DO NOT EDIT.
package foods

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client"
)

// _ suppresses unused import for packages where all methods use request structs.
var _ = url.Values{}

// Service provides typed access to the foods FatSecret API namespace.
type Service interface {
	// Autocomplete calls GET /rest/foods/autocomplete/v2. Auth: client_credentials. Scope: premier.
	Autocomplete(ctx context.Context, req AutocompleteRequest) (AutocompleteResult, error)
	// GetFavorites calls GET /rest/foods/favorites/v2. Auth: oauth1_delegated.
	GetFavorites(ctx context.Context) (FoodsResult, error)
	// GetMostEaten calls GET /rest/foods/most-eaten/v2. Auth: oauth1_delegated.
	GetMostEaten(ctx context.Context, req GetMostEatenRequest) (FoodsResult, error)
	// GetRecentlyEaten calls GET /rest/foods/recently-eaten/v2. Auth: oauth1_delegated.
	GetRecentlyEaten(ctx context.Context, req GetRecentlyEatenRequest) (FoodsResult, error)
	// Search calls GET /rest/foods/search/v3. Auth: client_credentials. Scope: premier.
	Search(ctx context.Context, req SearchRequest) (FoodsSearchResult, error)
	// SearchV5 calls GET /rest/foods/search/v5. Auth: client_credentials. Scope: basic.
	SearchV5(ctx context.Context, req SearchV5Request) (FoodsSearchResult, error)
}

type service struct{ c client.Client }

// New returns a Service bound to the given low-level client.
func New(c client.Client) Service { return &service{c: c} }

// Autocomplete implements Service.Autocomplete.
func (s *service) Autocomplete(ctx context.Context, req AutocompleteRequest) (AutocompleteResult, error) {
	var zero AutocompleteResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/foods/autocomplete/v2",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["suggestions"]
	if !ok {
		return zero, fmt.Errorf("foods.Autocomplete: response missing key %q", "suggestions")
	}
	var result AutocompleteResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("foods.Autocomplete: unmarshal: %w", err)
	}
	return result, nil
}

// GetFavorites implements Service.GetFavorites.
func (s *service) GetFavorites(ctx context.Context) (FoodsResult, error) {
	var zero FoodsResult
	params := url.Values{}
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/foods/favorites/v2",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["foods"]
	if !ok {
		return zero, fmt.Errorf("foods.GetFavorites: response missing key %q", "foods")
	}
	var result FoodsResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("foods.GetFavorites: unmarshal: %w", err)
	}
	return result, nil
}

// GetMostEaten implements Service.GetMostEaten.
func (s *service) GetMostEaten(ctx context.Context, req GetMostEatenRequest) (FoodsResult, error) {
	var zero FoodsResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/foods/most-eaten/v2",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["foods"]
	if !ok {
		return zero, fmt.Errorf("foods.GetMostEaten: response missing key %q", "foods")
	}
	var result FoodsResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("foods.GetMostEaten: unmarshal: %w", err)
	}
	return result, nil
}

// GetRecentlyEaten implements Service.GetRecentlyEaten.
func (s *service) GetRecentlyEaten(ctx context.Context, req GetRecentlyEatenRequest) (FoodsResult, error) {
	var zero FoodsResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/foods/recently-eaten/v2",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["foods"]
	if !ok {
		return zero, fmt.Errorf("foods.GetRecentlyEaten: response missing key %q", "foods")
	}
	var result FoodsResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("foods.GetRecentlyEaten: unmarshal: %w", err)
	}
	return result, nil
}

// Search implements Service.Search.
func (s *service) Search(ctx context.Context, req SearchRequest) (FoodsSearchResult, error) {
	var zero FoodsSearchResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/foods/search/v3",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["foods_search"]
	if !ok {
		return zero, fmt.Errorf("foods.Search: response missing key %q", "foods_search")
	}
	var result FoodsSearchResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("foods.Search: unmarshal: %w", err)
	}
	return result, nil
}

// SearchV5 implements Service.SearchV5.
func (s *service) SearchV5(ctx context.Context, req SearchV5Request) (FoodsSearchResult, error) {
	var zero FoodsSearchResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/foods/search/v5",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["foods_search"]
	if !ok {
		return zero, fmt.Errorf("foods.SearchV5: response missing key %q", "foods_search")
	}
	var result FoodsSearchResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("foods.SearchV5: unmarshal: %w", err)
	}
	return result, nil
}
