// Code generated by fsgen. DO NOT EDIT.
package foods_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	foods "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/api/foods"
	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client/mock"
)

// Suppress unused imports for packages where only compile-only tests are generated.
var (
	_ = context.Background
	_ = http.HandlerFunc(nil)
	_ = httptest.NewServer
	_ = strings.HasPrefix
	_ = mock.NewClient
)

// TestSmoke_foods_AutocompleteCompiles verifies the interface and request struct compile.
func TestSmoke_foods_AutocompleteCompiles(t *testing.T) {
	var _ foods.Service = foods.New(nil)
	_ = foods.AutocompleteRequest{}
}

// TestSmoke_foods_GetFavorites verifies GetFavorites dispatches correctly and unmarshals the smoke fixture.
func TestSmoke_foods_GetFavorites(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/rest/foods/favorites/v2") {
			t.Errorf("unexpected path %s, want prefix %s", r.URL.Path, "/rest/foods/favorites/v2")
		}
		if r.Method != "GET" {
			t.Errorf("unexpected method %s, want GET", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{\"foods\":{\"food\":[{\"food_id\":\"1641\",\"food_name\":\"Chicken Breast\",\"food_type\":\"Generic\",\"food_url\":\"https://www.fatsecret.com/calories-nutrition/generic/chicken-breast\"}]}}"))
	}))
	defer srv.Close()
	svc := foods.New(mock.NewClient(srv.URL))
	_, err := svc.GetFavorites(context.Background())
	if err != nil {
		t.Fatalf("GetFavorites returned error: %v", err)
	}
}

// TestSmoke_foods_GetMostEaten verifies GetMostEaten dispatches correctly and unmarshals the smoke fixture.
func TestSmoke_foods_GetMostEaten(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/rest/foods/most-eaten/v2") {
			t.Errorf("unexpected path %s, want prefix %s", r.URL.Path, "/rest/foods/most-eaten/v2")
		}
		if r.Method != "GET" {
			t.Errorf("unexpected method %s, want GET", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{\"foods\":{\"food\":[{\"food_id\":\"1641\",\"food_name\":\"Chicken Breast\",\"food_type\":\"Generic\",\"food_url\":\"https://www.fatsecret.com/calories-nutrition/generic/chicken-breast\"}]}}"))
	}))
	defer srv.Close()
	svc := foods.New(mock.NewClient(srv.URL))
	_, err := svc.GetMostEaten(context.Background(), foods.GetMostEatenRequest{})
	if err != nil {
		t.Fatalf("GetMostEaten returned error: %v", err)
	}
}

// TestSmoke_foods_GetRecentlyEaten verifies GetRecentlyEaten dispatches correctly and unmarshals the smoke fixture.
func TestSmoke_foods_GetRecentlyEaten(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/rest/foods/recently-eaten/v2") {
			t.Errorf("unexpected path %s, want prefix %s", r.URL.Path, "/rest/foods/recently-eaten/v2")
		}
		if r.Method != "GET" {
			t.Errorf("unexpected method %s, want GET", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{\"foods\":{\"food\":[{\"food_id\":\"1641\",\"food_name\":\"Chicken Breast\",\"food_type\":\"Generic\",\"food_url\":\"https://www.fatsecret.com/calories-nutrition/generic/chicken-breast\"}]}}"))
	}))
	defer srv.Close()
	svc := foods.New(mock.NewClient(srv.URL))
	_, err := svc.GetRecentlyEaten(context.Background(), foods.GetRecentlyEatenRequest{})
	if err != nil {
		t.Fatalf("GetRecentlyEaten returned error: %v", err)
	}
}

// TestSmoke_foods_Search verifies Search dispatches correctly and unmarshals the smoke fixture.
func TestSmoke_foods_Search(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/rest/foods/search/v3") {
			t.Errorf("unexpected path %s, want prefix %s", r.URL.Path, "/rest/foods/search/v3")
		}
		if r.Method != "GET" {
			t.Errorf("unexpected method %s, want GET", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{\"foods_search\":{\"max_results\":\"1\",\"total_results\":\"1\",\"page_number\":\"0\",\"results\":{\"food\":[{\"food_id\":\"1641\",\"food_name\":\"Chicken Breast\",\"food_type\":\"Generic\",\"food_url\":\"https://www.fatsecret.com/calories-nutrition/generic/chicken-breast\"}]}}}"))
	}))
	defer srv.Close()
	svc := foods.New(mock.NewClient(srv.URL))
	_, err := svc.Search(context.Background(), foods.SearchRequest{})
	if err != nil {
		t.Fatalf("Search returned error: %v", err)
	}
}

// TestSmoke_foods_SearchV5 verifies SearchV5 dispatches correctly and unmarshals the smoke fixture.
func TestSmoke_foods_SearchV5(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/rest/foods/search/v5") {
			t.Errorf("unexpected path %s, want prefix %s", r.URL.Path, "/rest/foods/search/v5")
		}
		if r.Method != "GET" {
			t.Errorf("unexpected method %s, want GET", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{\"foods_search\":{\"max_results\":\"1\",\"total_results\":\"1\",\"page_number\":\"0\",\"results\":{\"food\":[{\"food_id\":\"1641\",\"food_name\":\"Chicken Breast\",\"food_type\":\"Generic\",\"food_url\":\"https://www.fatsecret.com/calories-nutrition/generic/chicken-breast\"}]}}}"))
	}))
	defer srv.Close()
	svc := foods.New(mock.NewClient(srv.URL))
	_, err := svc.SearchV5(context.Background(), foods.SearchV5Request{})
	if err != nil {
		t.Fatalf("SearchV5 returned error: %v", err)
	}
}
