// Code generated by fsgen. DO NOT EDIT.
package recipes

import (
	"fmt"
	"net/url"
	"strconv"
	"time"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"
)

// Suppress unused imports for packages that may not be needed for all param types.
var (
	_ = fmt.Sprintf
	_ = strconv.FormatFloat
	_ = time.UTC
	_ = types.APIInt(0)
	_ = url.Values{}
)

// SearchRequest holds optional parameters for Search.
// Nil pointer fields are omitted from the request.
type SearchRequest struct {
	// SearchExpression maps to wire param "search_expression".
	SearchExpression *string
	// RecipeTypes maps to wire param "recipe_types".
	RecipeTypes *string
	// PageNumber maps to wire param "page_number".
	PageNumber *types.APIInt
	// MaxResults maps to wire param "max_results". Constraint: max=50.
	MaxResults *types.APIInt
	// SortBy maps to wire param "sort_by".
	SortBy *string
	// Region maps to wire param "region" (premier tier only).
	Region *string
	// Language maps to wire param "language".
	Language *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r SearchRequest) ToParams() url.Values {
	p := url.Values{}
	if r.SearchExpression != nil {
		p.Set("search_expression", (*r.SearchExpression))
	}
	if r.RecipeTypes != nil {
		p.Set("recipe_types", (*r.RecipeTypes))
	}
	if r.PageNumber != nil {
		p.Set("page_number", fmt.Sprintf("%d", int64((*r.PageNumber))))
	}
	if r.MaxResults != nil {
		p.Set("max_results", fmt.Sprintf("%d", int64((*r.MaxResults))))
	}
	if r.SortBy != nil {
		p.Set("sort_by", (*r.SortBy))
	}
	if r.Region != nil {
		p.Set("region", (*r.Region))
	}
	if r.Language != nil {
		p.Set("language", (*r.Language))
	}
	return p
}
