// Code generated by fsgen. DO NOT EDIT.
package recipes

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client"
)

// _ suppresses unused import for packages where all methods use request structs.
var _ = url.Values{}

// Service provides typed access to the recipes FatSecret API namespace.
type Service interface {
	// GetFavorites calls GET /rest/recipes/favorites/v2. Auth: oauth1_delegated.
	GetFavorites(ctx context.Context) (RecipesResult, error)
	// Search calls GET /rest/recipes/search/v3. Auth: client_credentials. Scope: basic.
	Search(ctx context.Context, req SearchRequest) (RecipesSearchResult, error)
}

type service struct{ c client.Client }

// New returns a Service bound to the given low-level client.
func New(c client.Client) Service { return &service{c: c} }

// GetFavorites implements Service.GetFavorites.
func (s *service) GetFavorites(ctx context.Context) (RecipesResult, error) {
	var zero RecipesResult
	params := url.Values{}
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/recipes/favorites/v2",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["recipes"]
	if !ok {
		return zero, fmt.Errorf("recipes.GetFavorites: response missing key %q", "recipes")
	}
	var result RecipesResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("recipes.GetFavorites: unmarshal: %w", err)
	}
	return result, nil
}

// Search implements Service.Search.
func (s *service) Search(ctx context.Context, req SearchRequest) (RecipesSearchResult, error) {
	var zero RecipesSearchResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/recipes/search/v3",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["recipes"]
	if !ok {
		return zero, fmt.Errorf("recipes.Search: response missing key %q", "recipes")
	}
	var result RecipesSearchResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("recipes.Search: unmarshal: %w", err)
	}
	return result, nil
}
