// Code generated by fsgen. DO NOT EDIT.
package recipes_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	recipes "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/api/recipes"
	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client/mock"
)

// Suppress unused imports for packages where only compile-only tests are generated.
var (
	_ = context.Background
	_ = http.HandlerFunc(nil)
	_ = httptest.NewServer
	_ = strings.HasPrefix
	_ = mock.NewClient
)

// TestSmoke_recipes_GetFavorites verifies GetFavorites dispatches correctly and unmarshals the smoke fixture.
func TestSmoke_recipes_GetFavorites(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/rest/recipes/favorites/v2") {
			t.Errorf("unexpected path %s, want prefix %s", r.URL.Path, "/rest/recipes/favorites/v2")
		}
		if r.Method != "GET" {
			t.Errorf("unexpected method %s, want GET", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{\"recipes\":{\"recipe\":[{\"recipe_id\":\"1\",\"recipe_name\":\"Grilled Chicken\",\"recipe_url\":\"https://www.fatsecret.com/recipes/grilled-chicken/Default.aspx\",\"recipe_nutrition\":{\"calories\":\"195\",\"carbohydrate\":\"0\",\"protein\":\"29\",\"fat\":\"8\"}}]}}"))
	}))
	defer srv.Close()
	svc := recipes.New(mock.NewClient(srv.URL))
	_, err := svc.GetFavorites(context.Background())
	if err != nil {
		t.Fatalf("GetFavorites returned error: %v", err)
	}
}

// TestSmoke_recipes_Search verifies Search dispatches correctly and unmarshals the smoke fixture.
func TestSmoke_recipes_Search(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/rest/recipes/search/v3") {
			t.Errorf("unexpected path %s, want prefix %s", r.URL.Path, "/rest/recipes/search/v3")
		}
		if r.Method != "GET" {
			t.Errorf("unexpected method %s, want GET", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{\"recipes\":{\"recipe\":[{\"recipe_id\":\"1\",\"recipe_name\":\"Grilled Chicken\",\"recipe_description\":\"Simple grilled chicken\",\"recipe_url\":\"https://www.fatsecret.com/recipes/grilled-chicken/Default.aspx\",\"recipe_nutrition\":{\"calories\":\"195\",\"carbohydrate\":\"0\",\"protein\":\"29\",\"fat\":\"8\"}}],\"max_results\":\"1\",\"total_results\":\"1\",\"page_number\":\"0\"}}"))
	}))
	defer srv.Close()
	svc := recipes.New(mock.NewClient(srv.URL))
	_, err := svc.Search(context.Background(), recipes.SearchRequest{})
	if err != nil {
		t.Fatalf("Search returned error: %v", err)
	}
}
