// Code generated by fsgen. DO NOT EDIT.
package recipe_types

import "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"

// Suppress unused import when all fields use string type.
var _ = types.APIInt(0)

// RecipeTypesResult is a generated response type for the recipe_types package.
type RecipeTypesResult struct {
	// RecipeType — Recipe type name list
	RecipeType types.FlexSlice[string] `json:"recipe_type,omitempty"`
}
