// Code generated by fsgen. DO NOT EDIT.
package recipe_types

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client"
)

// _ suppresses unused import for packages where all methods use request structs.
var _ = url.Values{}

// Service provides typed access to the recipe_types FatSecret API namespace.
type Service interface {
	// GetAll calls GET /rest/recipe-types/v2. Auth: client_credentials. Scope: basic.
	GetAll(ctx context.Context, req GetAllRequest) (RecipeTypesResult, error)
}

type service struct{ c client.Client }

// New returns a Service bound to the given low-level client.
func New(c client.Client) Service { return &service{c: c} }

// GetAll implements Service.GetAll.
func (s *service) GetAll(ctx context.Context, req GetAllRequest) (RecipeTypesResult, error) {
	var zero RecipeTypesResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/recipe-types/v2",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["recipe_types"]
	if !ok {
		return zero, fmt.Errorf("recipe_types.GetAll: response missing key %q", "recipe_types")
	}
	var result RecipeTypesResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("recipe_types.GetAll: unmarshal: %w", err)
	}
	return result, nil
}
