// Code generated by fsgen. DO NOT EDIT.
package recipe_types_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	recipe_types "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/api/recipe_types"
	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client/mock"
)

// Suppress unused imports for packages where only compile-only tests are generated.
var (
	_ = context.Background
	_ = http.HandlerFunc(nil)
	_ = httptest.NewServer
	_ = strings.HasPrefix
	_ = mock.NewClient
)

// TestSmoke_recipe_types_GetAll verifies GetAll dispatches correctly and unmarshals the smoke fixture.
func TestSmoke_recipe_types_GetAll(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/rest/recipe-types/v2") {
			t.Errorf("unexpected path %s, want prefix %s", r.URL.Path, "/rest/recipe-types/v2")
		}
		if r.Method != "GET" {
			t.Errorf("unexpected method %s, want GET", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{\"recipe_types\":{\"recipe_type\":[\"Breakfast\",\"Lunch\",\"Dinner\",\"Desserts\",\"Snacks\"]}}"))
	}))
	defer srv.Close()
	svc := recipe_types.New(mock.NewClient(srv.URL))
	_, err := svc.GetAll(context.Background(), recipe_types.GetAllRequest{})
	if err != nil {
		t.Fatalf("GetAll returned error: %v", err)
	}
}
