// Code generated by fsgen. DO NOT EDIT.
package recipe

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"
	"time"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"
)

// Suppress unused imports for packages that may not be needed for all param types.
var (
	_ = fmt.Sprintf
	_ = json.Marshal
	_ = strconv.FormatFloat
	_ = time.UTC
	_ = types.APIInt(0)
	_ = url.Values{}
)

// AddFavoriteRequest holds optional parameters for AddFavorite.
// Nil pointer fields are omitted from the request.
type AddFavoriteRequest struct {
	// RecipeID maps to wire param "recipe_id" (required).
	RecipeID *types.APIInt
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r AddFavoriteRequest) ToParams() url.Values {
	p := url.Values{}
	if r.RecipeID != nil {
		p.Set("recipe_id", fmt.Sprintf("%d", int64((*r.RecipeID))))
	}
	return p
}

// DeleteFavoriteRequest holds optional parameters for DeleteFavorite.
// Nil pointer fields are omitted from the request.
type DeleteFavoriteRequest struct {
	// RecipeID maps to wire param "recipe_id" (required).
	RecipeID *types.APIInt
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r DeleteFavoriteRequest) ToParams() url.Values {
	p := url.Values{}
	if r.RecipeID != nil {
		p.Set("recipe_id", fmt.Sprintf("%d", int64((*r.RecipeID))))
	}
	return p
}

// GetRequest holds optional parameters for Get.
// Nil pointer fields are omitted from the request.
type GetRequest struct {
	// RecipeID maps to wire param "recipe_id" (required).
	RecipeID *types.APIInt
	// Region maps to wire param "region" (premier tier only).
	Region *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r GetRequest) ToParams() url.Values {
	p := url.Values{}
	if r.RecipeID != nil {
		p.Set("recipe_id", fmt.Sprintf("%d", int64((*r.RecipeID))))
	}
	if r.Region != nil {
		p.Set("region", (*r.Region))
	}
	return p
}
