// Code generated by fsgen. DO NOT EDIT.
package recipe

import "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"

// Suppress unused import when all fields use string type.
var _ = types.APIInt(0)

// Recipe is a generated response type for the recipe package.
type Recipe struct {
	// CookingTimeMin — Cook time in minutes
	CookingTimeMin *types.APIInt `json:"cooking_time_min,omitempty"`
	// Directions — Preparation directions
	Directions types.FlexSlice[RecipeDirection] `json:"directions,omitempty"`
	// Ingredients — Ingredient list
	Ingredients types.FlexSlice[RecipeIngredient] `json:"ingredients,omitempty"`
	// NumberOfServings — Number of servings the recipe yields
	NumberOfServings *types.APIFloat `json:"number_of_servings,omitempty"`
	// PreparationTimeMin — Prep time in minutes
	PreparationTimeMin *types.APIInt `json:"preparation_time_min,omitempty"`
	// Rating — Community rating 0–5
	Rating *types.APIInt `json:"rating,omitempty"`
	// RecipeCategories — Recipe category objects
	RecipeCategories types.FlexSlice[RecipeCategory] `json:"recipe_categories,omitempty"`
	// RecipeDescription — Short description; absent for user-created recipes
	RecipeDescription *string `json:"recipe_description,omitempty"`
	// RecipeID — Unique recipe identifier
	RecipeID types.APIInt `json:"recipe_id"`
	// RecipeImage — Primary recipe image URL
	RecipeImage *string `json:"recipe_image,omitempty"`
	// RecipeImages — Additional recipe image URLs
	RecipeImages types.FlexSlice[string] `json:"recipe_images,omitempty"`
	// RecipeName — Recipe display name
	RecipeName string `json:"recipe_name"`
	// RecipeNutrition — Aggregate nutritional info per serving
	RecipeNutrition RecipeNutrition `json:"recipe_nutrition"`
	// RecipeTypes — Recipe type labels (e.g. Desserts)
	RecipeTypes types.FlexSlice[string] `json:"recipe_types,omitempty"`
	// RecipeURL — FatSecret URL for the recipe
	RecipeURL string `json:"recipe_url"`
	// ServingSizes — Per-serving nutritional breakdown
	ServingSizes types.FlexSlice[RecipeServing] `json:"serving_sizes,omitempty"`
}

// RecipeCategory is a generated response type for the recipe package.
type RecipeCategory struct {
	// RecipeCategoryName — Category label
	RecipeCategoryName string `json:"recipe_category_name"`
	// RecipeCategoryURL — FatSecret URL for the category
	RecipeCategoryURL *string `json:"recipe_category_url,omitempty"`
}

// RecipeDirection is a generated response type for the recipe package.
type RecipeDirection struct {
	// DirectionDescription — Step instructions
	DirectionDescription string `json:"direction_description"`
	// DirectionNumber — Step number (1-based)
	DirectionNumber types.APIInt `json:"direction_number"`
}

// RecipeIngredient is a generated response type for the recipe package.
type RecipeIngredient struct {
	// FoodID — Food identifier for the ingredient
	FoodID types.APIInt `json:"food_id"`
	// FoodName — Ingredient name
	FoodName string `json:"food_name"`
	// IngredientDescription — Full text ingredient description
	IngredientDescription *string `json:"ingredient_description,omitempty"`
	// MeasurementDescription — Unit description
	MeasurementDescription *string `json:"measurement_description,omitempty"`
	// NumberOfUnits — Quantity of servings
	NumberOfUnits *types.APIFloat `json:"number_of_units,omitempty"`
	// ServingID — Serving used for this ingredient
	ServingID *types.APIInt `json:"serving_id,omitempty"`
}

// RecipeNutrition is a generated response type for the recipe package.
type RecipeNutrition struct {
	// Calories — Calories per serving
	Calories types.APIFloat `json:"calories"`
	// Carbohydrate — Carbohydrate per serving in grams
	Carbohydrate types.APIFloat `json:"carbohydrate"`
	// Fat — Fat per serving in grams
	Fat types.APIFloat `json:"fat"`
	// Protein — Protein per serving in grams
	Protein types.APIFloat `json:"protein"`
}

// RecipeServing is a generated response type for the recipe package.
type RecipeServing struct {
	// Calories — Calories for this serving
	Calories types.APIFloat `json:"calories"`
	// Carbohydrate — Carbohydrate in grams
	Carbohydrate types.APIFloat `json:"carbohydrate"`
	// Fat — Fat in grams
	Fat types.APIFloat `json:"fat"`
	// Protein — Protein in grams
	Protein types.APIFloat `json:"protein"`
	// ServingSize — Human-readable serving size
	ServingSize string `json:"serving_size"`
}

// SuccessResult is a generated response type for the recipe package.
type SuccessResult struct {
	// Success — 1 on success
	Success types.APIInt `json:"success"`
}
