// Code generated by fsgen. DO NOT EDIT.
package recipe

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client"
)

// _ suppresses unused import for packages where all methods use request structs.
var _ = url.Values{}

// Service provides typed access to the recipe FatSecret API namespace.
type Service interface {
	// AddFavorite calls POST /rest/recipe/favorite/v1. Auth: oauth1_delegated.
	AddFavorite(ctx context.Context, req AddFavoriteRequest) (SuccessResult, error)
	// DeleteFavorite calls DELETE /rest/recipe/favorite/v1. Auth: oauth1_delegated.
	DeleteFavorite(ctx context.Context, req DeleteFavoriteRequest) (SuccessResult, error)
	// Get calls GET /rest/recipe/v2. Auth: client_credentials. Scope: basic.
	Get(ctx context.Context, req GetRequest) (Recipe, error)
}

type service struct{ c client.Client }

// New returns a Service bound to the given low-level client.
func New(c client.Client) Service { return &service{c: c} }

// AddFavorite implements Service.AddFavorite.
func (s *service) AddFavorite(ctx context.Context, req AddFavoriteRequest) (SuccessResult, error) {
	var zero SuccessResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "POST",
		Path:   "/rest/recipe/favorite/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["success"]
	if !ok {
		return zero, fmt.Errorf("recipe.AddFavorite: response missing key %q", "success")
	}
	var result SuccessResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("recipe.AddFavorite: unmarshal: %w", err)
	}
	return result, nil
}

// DeleteFavorite implements Service.DeleteFavorite.
func (s *service) DeleteFavorite(ctx context.Context, req DeleteFavoriteRequest) (SuccessResult, error) {
	var zero SuccessResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "DELETE",
		Path:   "/rest/recipe/favorite/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["success"]
	if !ok {
		return zero, fmt.Errorf("recipe.DeleteFavorite: response missing key %q", "success")
	}
	var result SuccessResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("recipe.DeleteFavorite: unmarshal: %w", err)
	}
	return result, nil
}

// Get implements Service.Get.
func (s *service) Get(ctx context.Context, req GetRequest) (Recipe, error) {
	var zero Recipe
	params := req.ToParams()
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/recipe/v2",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["recipe"]
	if !ok {
		return zero, fmt.Errorf("recipe.Get: response missing key %q", "recipe")
	}
	var result Recipe
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("recipe.Get: unmarshal: %w", err)
	}
	return result, nil
}
