// Code generated by fsgen. DO NOT EDIT.
package recipe_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	recipe "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/api/recipe"
	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client/mock"
)

// Suppress unused imports for packages where only compile-only tests are generated.
var (
	_ = context.Background
	_ = http.HandlerFunc(nil)
	_ = httptest.NewServer
	_ = strings.HasPrefix
	_ = mock.NewClient
)

// TestSmoke_recipe_AddFavoriteCompiles verifies the interface and request struct compile.
func TestSmoke_recipe_AddFavoriteCompiles(t *testing.T) {
	var _ recipe.Service = recipe.New(nil)
	_ = recipe.AddFavoriteRequest{}
}

// TestSmoke_recipe_DeleteFavoriteCompiles verifies the interface and request struct compile.
func TestSmoke_recipe_DeleteFavoriteCompiles(t *testing.T) {
	var _ recipe.Service = recipe.New(nil)
	_ = recipe.DeleteFavoriteRequest{}
}

// TestSmoke_recipe_GetCompiles verifies the interface and request struct compile.
func TestSmoke_recipe_GetCompiles(t *testing.T) {
	var _ recipe.Service = recipe.New(nil)
	_ = recipe.GetRequest{}
}
