// Code generated by fsgen. DO NOT EDIT.
package weight

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"
	"time"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"
)

// Suppress unused imports for packages that may not be needed for all param types.
var (
	_ = fmt.Sprintf
	_ = json.Marshal
	_ = strconv.FormatFloat
	_ = time.UTC
	_ = types.APIInt(0)
	_ = url.Values{}
)

// GetMonthRequest holds optional parameters for GetMonth.
// Nil pointer fields are omitted from the request.
type GetMonthRequest struct {
	// Date maps to wire param "date".
	Date *types.APIDaysEpoch
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r GetMonthRequest) ToParams() url.Values {
	p := url.Values{}
	if r.Date != nil {
		p.Set("date", func() string {
			t := time.Time((*r.Date))
			days := int64(t.Sub(time.Date(1970, 1, 1, 0, 0, 0, 0, time.UTC)) / (24 * time.Hour))
			return fmt.Sprintf("%d", days)
		}())
	}
	return p
}

// UpdateRequest holds optional parameters for Update.
// Nil pointer fields are omitted from the request.
type UpdateRequest struct {
	// CurrentWeightKg maps to wire param "current_weight_kg" (required).
	CurrentWeightKg *types.APIFloat
	// Date maps to wire param "date".
	Date *types.APIDaysEpoch
	// GoalWeightKg maps to wire param "goal_weight_kg".
	GoalWeightKg *types.APIFloat
	// CurrentHeightCm maps to wire param "current_height_cm".
	CurrentHeightCm *types.APIFloat
	// Comment maps to wire param "comment".
	Comment *string
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r UpdateRequest) ToParams() url.Values {
	p := url.Values{}
	if r.CurrentWeightKg != nil {
		p.Set("current_weight_kg", strconv.FormatFloat(float64((*r.CurrentWeightKg)), 'f', -1, 64))
	}
	if r.Date != nil {
		p.Set("date", func() string {
			t := time.Time((*r.Date))
			days := int64(t.Sub(time.Date(1970, 1, 1, 0, 0, 0, 0, time.UTC)) / (24 * time.Hour))
			return fmt.Sprintf("%d", days)
		}())
	}
	if r.GoalWeightKg != nil {
		p.Set("goal_weight_kg", strconv.FormatFloat(float64((*r.GoalWeightKg)), 'f', -1, 64))
	}
	if r.CurrentHeightCm != nil {
		p.Set("current_height_cm", strconv.FormatFloat(float64((*r.CurrentHeightCm)), 'f', -1, 64))
	}
	if r.Comment != nil {
		p.Set("comment", (*r.Comment))
	}
	return p
}
