// Code generated by fsgen. DO NOT EDIT.
package weight

import "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"

// Suppress unused import when all fields use string type.
var _ = types.APIInt(0)

// SuccessResult is a generated response type for the weight package.
type SuccessResult struct {
	// Success — 1 on success
	Success types.APIInt `json:"success"`
}

// WeightEntry is a generated response type for the weight package.
type WeightEntry struct {
	// DateInt — Days since 1970-01-01
	DateInt types.APIDaysEpoch `json:"date_int"`
	// WeightComment — Optional free-text comment
	WeightComment *string `json:"weight_comment,omitempty"`
	// WeightKg — Weight in kilograms
	WeightKg types.APIFloat `json:"weight_kg"`
}

// WeightMonthResult is a generated response type for the weight package.
type WeightMonthResult struct {
	// Day — Per-day weight entries
	Day types.FlexSlice[WeightEntry] `json:"day,omitempty"`
	// Month — Month number string
	Month string `json:"month"`
}
