// Code generated by fsgen. DO NOT EDIT.
package weight

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client"
)

// _ suppresses unused import for packages where all methods use request structs.
var _ = url.Values{}

// Service provides typed access to the weight FatSecret API namespace.
type Service interface {
	// GetMonth calls GET /rest/weights/get-month/v2. Auth: oauth1_delegated.
	GetMonth(ctx context.Context, req GetMonthRequest) (WeightMonthResult, error)
	// Update calls POST /rest/weight/v1. Auth: oauth1_delegated.
	Update(ctx context.Context, req UpdateRequest) (SuccessResult, error)
}

type service struct{ c client.Client }

// New returns a Service bound to the given low-level client.
func New(c client.Client) Service { return &service{c: c} }

// GetMonth implements Service.GetMonth.
func (s *service) GetMonth(ctx context.Context, req GetMonthRequest) (WeightMonthResult, error) {
	var zero WeightMonthResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/weights/get-month/v2",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["month"]
	if !ok {
		return zero, fmt.Errorf("weight.GetMonth: response missing key %q", "month")
	}
	var result WeightMonthResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("weight.GetMonth: unmarshal: %w", err)
	}
	return result, nil
}

// Update implements Service.Update.
func (s *service) Update(ctx context.Context, req UpdateRequest) (SuccessResult, error) {
	var zero SuccessResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "POST",
		Path:   "/rest/weight/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["success"]
	if !ok {
		return zero, fmt.Errorf("weight.Update: response missing key %q", "success")
	}
	var result SuccessResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("weight.Update: unmarshal: %w", err)
	}
	return result, nil
}
