// Code generated by fsgen. DO NOT EDIT.
package weight_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	weight "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/api/weight"
	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client/mock"
)

// Suppress unused imports for packages where only compile-only tests are generated.
var (
	_ = context.Background
	_ = http.HandlerFunc(nil)
	_ = httptest.NewServer
	_ = strings.HasPrefix
	_ = mock.NewClient
)

// TestSmoke_weight_GetMonth verifies GetMonth dispatches correctly and unmarshals the smoke fixture.
func TestSmoke_weight_GetMonth(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/rest/weights/get-month/v2") {
			t.Errorf("unexpected path %s, want prefix %s", r.URL.Path, "/rest/weights/get-month/v2")
		}
		if r.Method != "GET" {
			t.Errorf("unexpected method %s, want GET", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{\"month\":{\"day\":[{\"date_int\":\"14289\",\"weight_kg\":\"75.5\",\"weight_comment\":\"Morning weight\"}]}}"))
	}))
	defer srv.Close()
	svc := weight.New(mock.NewClient(srv.URL))
	_, err := svc.GetMonth(context.Background(), weight.GetMonthRequest{})
	if err != nil {
		t.Fatalf("GetMonth returned error: %v", err)
	}
}

// TestSmoke_weight_UpdateCompiles verifies the interface and request struct compile.
func TestSmoke_weight_UpdateCompiles(t *testing.T) {
	var _ weight.Service = weight.New(nil)
	_ = weight.UpdateRequest{}
}
