// Code generated by fsgen. DO NOT EDIT.
package exercise_entries

import (
	"fmt"
	"net/url"
	"strconv"
	"time"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"
)

// Suppress unused imports for packages that may not be needed for all param types.
var (
	_ = fmt.Sprintf
	_ = strconv.FormatFloat
	_ = time.UTC
	_ = types.APIInt(0)
	_ = url.Values{}
)

// CommitDayRequest holds optional parameters for CommitDay.
// Nil pointer fields are omitted from the request.
type CommitDayRequest struct {
	// Date maps to wire param "date".
	Date *types.APIDaysEpoch
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r CommitDayRequest) ToParams() url.Values {
	p := url.Values{}
	if r.Date != nil {
		p.Set("date", func() string {
			t := time.Time((*r.Date))
			days := int64(t.Sub(time.Date(1970, 1, 1, 0, 0, 0, 0, time.UTC)) / (24 * time.Hour))
			return fmt.Sprintf("%d", days)
		}())
	}
	return p
}

// EditRequest holds optional parameters for Edit.
// Nil pointer fields are omitted from the request.
type EditRequest struct {
	// ShiftToID maps to wire param "shift_to_id" (required).
	ShiftToID *types.APIInt
	// ShiftFromID maps to wire param "shift_from_id" (required).
	ShiftFromID *types.APIInt
	// Minutes maps to wire param "minutes" (required).
	Minutes *types.APIFloat
	// Date maps to wire param "date".
	Date *types.APIDaysEpoch
	// ShiftToName maps to wire param "shift_to_name".
	ShiftToName *string
	// ShiftFromName maps to wire param "shift_from_name".
	ShiftFromName *string
	// Kcal maps to wire param "kcal".
	Kcal *types.APIFloat
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r EditRequest) ToParams() url.Values {
	p := url.Values{}
	if r.ShiftToID != nil {
		p.Set("shift_to_id", fmt.Sprintf("%d", int64((*r.ShiftToID))))
	}
	if r.ShiftFromID != nil {
		p.Set("shift_from_id", fmt.Sprintf("%d", int64((*r.ShiftFromID))))
	}
	if r.Minutes != nil {
		p.Set("minutes", strconv.FormatFloat(float64((*r.Minutes)), 'f', -1, 64))
	}
	if r.Date != nil {
		p.Set("date", func() string {
			t := time.Time((*r.Date))
			days := int64(t.Sub(time.Date(1970, 1, 1, 0, 0, 0, 0, time.UTC)) / (24 * time.Hour))
			return fmt.Sprintf("%d", days)
		}())
	}
	if r.ShiftToName != nil {
		p.Set("shift_to_name", (*r.ShiftToName))
	}
	if r.ShiftFromName != nil {
		p.Set("shift_from_name", (*r.ShiftFromName))
	}
	if r.Kcal != nil {
		p.Set("kcal", strconv.FormatFloat(float64((*r.Kcal)), 'f', -1, 64))
	}
	return p
}

// GetRequest holds optional parameters for Get.
// Nil pointer fields are omitted from the request.
type GetRequest struct {
	// Date maps to wire param "date".
	Date *types.APIDaysEpoch
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r GetRequest) ToParams() url.Values {
	p := url.Values{}
	if r.Date != nil {
		p.Set("date", func() string {
			t := time.Time((*r.Date))
			days := int64(t.Sub(time.Date(1970, 1, 1, 0, 0, 0, 0, time.UTC)) / (24 * time.Hour))
			return fmt.Sprintf("%d", days)
		}())
	}
	return p
}

// SaveTemplateRequest holds optional parameters for SaveTemplate.
// Nil pointer fields are omitted from the request.
type SaveTemplateRequest struct {
	// Days maps to wire param "days" (required).
	Days *types.APIInt
}

// ToParams encodes set fields into a url.Values map.
// Required fields that are nil are not validated here; the server will reject them.
func (r SaveTemplateRequest) ToParams() url.Values {
	p := url.Values{}
	if r.Days != nil {
		p.Set("days", fmt.Sprintf("%d", int64((*r.Days))))
	}
	return p
}
