// Code generated by fsgen. DO NOT EDIT.
package exercise_entries

import "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/types"

// Suppress unused import when all fields use string type.
var _ = types.APIInt(0)

// ExerciseEntriesResult is a generated response type for the exercise_entries package.
type ExerciseEntriesResult struct {
	// ExerciseEntry — Logged exercise entries
	ExerciseEntry types.FlexSlice[ExerciseEntry] `json:"exercise_entry,omitempty"`
}

// ExerciseEntry is a generated response type for the exercise_entries package.
type ExerciseEntry struct {
	// Kcal — Calories burned
	Kcal types.APIFloat `json:"kcal"`
	// Minutes — Duration in minutes
	Minutes types.APIFloat `json:"minutes"`
	// ShiftToID — Exercise type identifier (0 for custom)
	ShiftToID types.APIInt `json:"shift_to_id"`
	// ShiftToName — Exercise type name
	ShiftToName string `json:"shift_to_name"`
}

// SuccessResult is a generated response type for the exercise_entries package.
type SuccessResult struct {
	// Success — 1 on success
	Success types.APIInt `json:"success"`
}
