// Code generated by fsgen. DO NOT EDIT.
package exercise_entries

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"

	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client"
)

// _ suppresses unused import for packages where all methods use request structs.
var _ = url.Values{}

// Service provides typed access to the exercise_entries FatSecret API namespace.
type Service interface {
	// CommitDay calls POST /rest/exercise-entries/commit-day/v1. Auth: oauth1_delegated.
	CommitDay(ctx context.Context, req CommitDayRequest) (SuccessResult, error)
	// Edit calls PUT /rest/exercise-entry/v1. Auth: oauth1_delegated.
	Edit(ctx context.Context, req EditRequest) (SuccessResult, error)
	// Get calls GET /rest/exercise-entries/v1. Auth: oauth1_delegated.
	Get(ctx context.Context, req GetRequest) (ExerciseEntriesResult, error)
	// SaveTemplate calls POST /rest/exercise-entries/save-template/v1. Auth: oauth1_delegated.
	SaveTemplate(ctx context.Context, req SaveTemplateRequest) (SuccessResult, error)
}

type service struct{ c client.Client }

// New returns a Service bound to the given low-level client.
func New(c client.Client) Service { return &service{c: c} }

// CommitDay implements Service.CommitDay.
func (s *service) CommitDay(ctx context.Context, req CommitDayRequest) (SuccessResult, error) {
	var zero SuccessResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "POST",
		Path:   "/rest/exercise-entries/commit-day/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["success"]
	if !ok {
		return zero, fmt.Errorf("exercise_entries.CommitDay: response missing key %q", "success")
	}
	var result SuccessResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("exercise_entries.CommitDay: unmarshal: %w", err)
	}
	return result, nil
}

// Edit implements Service.Edit.
func (s *service) Edit(ctx context.Context, req EditRequest) (SuccessResult, error) {
	var zero SuccessResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "PUT",
		Path:   "/rest/exercise-entry/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["success"]
	if !ok {
		return zero, fmt.Errorf("exercise_entries.Edit: response missing key %q", "success")
	}
	var result SuccessResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("exercise_entries.Edit: unmarshal: %w", err)
	}
	return result, nil
}

// Get implements Service.Get.
func (s *service) Get(ctx context.Context, req GetRequest) (ExerciseEntriesResult, error) {
	var zero ExerciseEntriesResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "GET",
		Path:   "/rest/exercise-entries/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["exercise_entries"]
	if !ok {
		return zero, fmt.Errorf("exercise_entries.Get: response missing key %q", "exercise_entries")
	}
	var result ExerciseEntriesResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("exercise_entries.Get: unmarshal: %w", err)
	}
	return result, nil
}

// SaveTemplate implements Service.SaveTemplate.
func (s *service) SaveTemplate(ctx context.Context, req SaveTemplateRequest) (SuccessResult, error) {
	var zero SuccessResult
	params := req.ToParams()
	creq := &client.Request{
		Method: "POST",
		Path:   "/rest/exercise-entries/save-template/v1",
		Params: params,
	}
	var env map[string]json.RawMessage
	if _, err := client.DoJSON(ctx, s.c, creq, &env); err != nil {
		return zero, err
	}
	raw, ok := env["success"]
	if !ok {
		return zero, fmt.Errorf("exercise_entries.SaveTemplate: response missing key %q", "success")
	}
	var result SuccessResult
	if err := json.Unmarshal(raw, &result); err != nil {
		return zero, fmt.Errorf("exercise_entries.SaveTemplate: unmarshal: %w", err)
	}
	return result, nil
}
