// Code generated by fsgen. DO NOT EDIT.
package exercise_entries_test

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	exercise_entries "github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/api/exercise_entries"
	"github.com/fivetwenty-io/fatsecret-apiclient-go/pkg/client/mock"
)

// Suppress unused imports for packages where only compile-only tests are generated.
var (
	_ = context.Background
	_ = http.HandlerFunc(nil)
	_ = httptest.NewServer
	_ = strings.HasPrefix
	_ = mock.NewClient
)

// TestSmoke_exercise_entries_CommitDay verifies CommitDay dispatches correctly and unmarshals the smoke fixture.
func TestSmoke_exercise_entries_CommitDay(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/rest/exercise-entries/commit-day/v1") {
			t.Errorf("unexpected path %s, want prefix %s", r.URL.Path, "/rest/exercise-entries/commit-day/v1")
		}
		if r.Method != "POST" {
			t.Errorf("unexpected method %s, want POST", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{\"success\":{\"success\":\"1\"}}"))
	}))
	defer srv.Close()
	svc := exercise_entries.New(mock.NewClient(srv.URL))
	_, err := svc.CommitDay(context.Background(), exercise_entries.CommitDayRequest{})
	if err != nil {
		t.Fatalf("CommitDay returned error: %v", err)
	}
}

// TestSmoke_exercise_entries_EditCompiles verifies the interface and request struct compile.
func TestSmoke_exercise_entries_EditCompiles(t *testing.T) {
	var _ exercise_entries.Service = exercise_entries.New(nil)
	_ = exercise_entries.EditRequest{}
}

// TestSmoke_exercise_entries_Get verifies Get dispatches correctly and unmarshals the smoke fixture.
func TestSmoke_exercise_entries_Get(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/rest/exercise-entries/v1") {
			t.Errorf("unexpected path %s, want prefix %s", r.URL.Path, "/rest/exercise-entries/v1")
		}
		if r.Method != "GET" {
			t.Errorf("unexpected method %s, want GET", r.Method)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte("{\"exercise_entries\":{\"exercise_entry\":[{\"shift_to_id\":\"1\",\"shift_to_name\":\"Running\",\"kcal\":\"300\",\"minutes\":\"30\"}]}}"))
	}))
	defer srv.Close()
	svc := exercise_entries.New(mock.NewClient(srv.URL))
	_, err := svc.Get(context.Background(), exercise_entries.GetRequest{})
	if err != nil {
		t.Fatalf("Get returned error: %v", err)
	}
}

// TestSmoke_exercise_entries_SaveTemplateCompiles verifies the interface and request struct compile.
func TestSmoke_exercise_entries_SaveTemplateCompiles(t *testing.T) {
	var _ exercise_entries.Service = exercise_entries.New(nil)
	_ = exercise_entries.SaveTemplateRequest{}
}
