// Package compatibility provides runtime lookup of FatSecret API method versioning
// metadata sourced from the generated Matrix catalog.
//
// The Matrix variable (in matrix.go, generated by fsgen) lists every known API
// method with its namespace, supported version integers, deprecated version integers,
// authentication tier, and required OAuth 2.0 scope.
//
// Use [NewChecker] to build an indexed view of the Matrix and then query it:
//
//	checker := compatibility.NewChecker()
//
//	// Test whether a method exists.
//	checker.Supports("foods", "search") // true
//
//	// Find the current non-deprecated version.
//	ver, ok := checker.LatestVersion("foods", "search") // "5", true
//
//	// Check whether a specific version is deprecated.
//	checker.IsDeprecated("foods", "search", "1") // true
//
//	// Retrieve the required OAuth 2.0 scope for a method.
//	scope, ok := checker.RequiresScope("foods", "autocomplete") // "premier", true
//
//	// Retrieve the authentication tier.
//	tier, ok := checker.RequiresAuth("food_entries", "create") // "oauth1_delegated", true
//
// A [Checker] is read-only after construction and safe for concurrent use by
// multiple goroutines. The underlying Matrix slice is also read-only at runtime
// because it is generated as a package-level var; callers must not modify it.
package compatibility
