// Code generated by fsgen. DO NOT EDIT.
package compatibility

// Entry describes versioning metadata for one API method.
type Entry struct {
	Namespace  string
	Name       string
	Versions   []int
	Deprecated []int
	AuthTier   string
	Scope      string
}

// Matrix is the complete catalog of all FatSecret API methods known to this client.
var Matrix = []Entry{
	{Namespace: "exercise_entries", Name: "commit_day", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "exercise_entries", Name: "edit", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "exercise_entries", Name: "get", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "exercise_entries", Name: "save_template", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "exercises", Name: "get", Versions: []int{1, 2}, Deprecated: []int{1}, AuthTier: "client_credentials", Scope: "basic"},
	{Namespace: "feedback", Name: "submit", Versions: []int{1}, Deprecated: []int{}, AuthTier: "client_credentials", Scope: "feedback"},
	{Namespace: "food", Name: "add_favorite", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "food", Name: "create", Versions: []int{2}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "food", Name: "delete_favorite", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "food", Name: "find_id_for_barcode", Versions: []int{2}, Deprecated: []int{}, AuthTier: "client_credentials", Scope: "barcode"},
	{Namespace: "food", Name: "get", Versions: []int{2, 3, 4, 5}, Deprecated: []int{2, 3}, AuthTier: "client_credentials", Scope: "basic"},
	{Namespace: "food_brands", Name: "get_all", Versions: []int{2}, Deprecated: []int{}, AuthTier: "client_credentials", Scope: "premier"},
	{Namespace: "food_categories", Name: "get_all", Versions: []int{2}, Deprecated: []int{}, AuthTier: "client_credentials", Scope: "premier"},
	{Namespace: "food_entries", Name: "copy", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "food_entries", Name: "create", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "food_entries", Name: "delete", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "food_entries", Name: "edit", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "food_entries", Name: "get", Versions: []int{1, 2}, Deprecated: []int{1}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "food_entries", Name: "get_month", Versions: []int{1, 2}, Deprecated: []int{1}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "food_sub_categories", Name: "get_all", Versions: []int{2}, Deprecated: []int{}, AuthTier: "client_credentials", Scope: "premier"},
	{Namespace: "foods", Name: "autocomplete", Versions: []int{2}, Deprecated: []int{}, AuthTier: "client_credentials", Scope: "premier"},
	{Namespace: "foods", Name: "search", Versions: []int{1, 3, 5}, Deprecated: []int{1}, AuthTier: "client_credentials", Scope: "basic"},
	{Namespace: "foods_favorites", Name: "get_favorites", Versions: []int{2}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "foods_favorites", Name: "get_most_eaten", Versions: []int{2}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "foods_favorites", Name: "get_recently_eaten", Versions: []int{2}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "native", Name: "nlp", Versions: []int{1}, Deprecated: []int{}, AuthTier: "client_credentials", Scope: "nlp"},
	{Namespace: "native", Name: "recognize", Versions: []int{2}, Deprecated: []int{}, AuthTier: "client_credentials", Scope: "image-recognition"},
	{Namespace: "profile", Name: "create", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_signed", Scope: ""},
	{Namespace: "profile", Name: "get", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "profile", Name: "get_auth", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_signed", Scope: ""},
	{Namespace: "recipe", Name: "add_favorite", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "recipe", Name: "delete_favorite", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "recipe", Name: "get", Versions: []int{1, 2}, Deprecated: []int{1}, AuthTier: "client_credentials", Scope: "basic"},
	{Namespace: "recipe_types", Name: "get_all", Versions: []int{2}, Deprecated: []int{}, AuthTier: "client_credentials", Scope: "basic"},
	{Namespace: "recipes", Name: "search", Versions: []int{1, 2, 3}, Deprecated: []int{1, 2}, AuthTier: "client_credentials", Scope: "basic"},
	{Namespace: "recipes_favorites", Name: "get_favorites", Versions: []int{2}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "saved_meals", Name: "add_item", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "saved_meals", Name: "create", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "saved_meals", Name: "delete", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "saved_meals", Name: "delete_item", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "saved_meals", Name: "edit", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "saved_meals", Name: "edit_item", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "saved_meals", Name: "get", Versions: []int{1, 2}, Deprecated: []int{1}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "saved_meals", Name: "get_items", Versions: []int{2}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "weight", Name: "update", Versions: []int{1}, Deprecated: []int{}, AuthTier: "oauth1_delegated", Scope: ""},
	{Namespace: "weights", Name: "get_month", Versions: []int{1, 2}, Deprecated: []int{1}, AuthTier: "oauth1_delegated", Scope: ""},
}
